"""Expected STK controller signatures from the official Csound opcode manuals."""

STK_CONTROLLERS: dict[str, list[tuple[str, int]]] = {
    "STKBandedWG": [("kpress", 2), ("kmot", 4), ("klfo", 11), ("klfodepth", 1), ("kvel", 128), ("kstrk", 64), ("kinstr", 16)],
    "STKBeeThree": [("kop4", 2), ("kop3", 4), ("klfo", 11), ("klfodepth", 1), ("kadsr", 128)],
    "STKBlowBotl": [("knoise", 4), ("klfo", 11), ("klfodepth", 1), ("kvol", 128)],
    "STKBlowHole": [("kreed", 2), ("knoise", 4), ("khole", 11), ("kreg", 1), ("kbreath", 128)],
    "STKBowed": [("kpress", 2), ("kpos", 4), ("klfo", 11), ("klfodepth", 1), ("kvol", 128)],
    "STKBrass": [("klip", 2), ("kslide", 4), ("klfo", 11), ("klfodepth", 1), ("kvol", 128)],
    "STKClarinet": [("kstiff", 2), ("knoise", 4), ("klfo", 11), ("klfodepth", 1), ("kbreath", 128)],
    "STKDrummer": [],
    "STKFlute": [("kjet", 2), ("knoise", 4), ("klfo", 11), ("klfodepth", 1), ("kbreath", 128)],
    "STKFMVoices": [("kvowel", 2), ("kspec", 4), ("klfo", 11), ("klfodepth", 1), ("kadsr", 128)],
    "STKHevyMetl": [("kmod", 2), ("kcross", 4), ("klfo", 11), ("klfodepth", 1), ("kadsr", 128)],
    "STKMandolin": [("kbody", 2), ("kpos", 4), ("ksus", 11), ("kdetune", 1), ("kmic", 128)],
    "STKModalBar": [("khard", 2), ("kpos", 4), ("klfo", 11), ("klfodepth", 1), ("kmix", 8), ("kvol", 128), ("kinstr", 16)],
    "STKMoog": [("kq", 2), ("krate", 4), ("klfo", 11), ("klfodepth", 1), ("kvol", 128)],
    "STKPercFlut": [("kmod", 2), ("kcross", 4), ("klfo", 11), ("klfodepth", 1), ("kadsr", 128)],
    "STKPlucked": [],
    "STKResonate": [("kfreq", 2), ("kpole", 4), ("knotch", 11), ("kzero", 1), ("kenv", 128)],
    "STKRhodey": [("kmod", 2), ("kcross", 4), ("klfo", 11), ("klfodepth", 1), ("kadsr", 128)],
    "STKSaxofony": [("kstiff", 2), ("kapert", 26), ("kblow", 11), ("knoise", 4), ("klfo", 29), ("klfodepth", 1), ("kbreath", 128)],
    "STKShakers": [("kenerg", 2), ("kdecay", 4), ("kshake", 128), ("knum", 11), ("kres", 1), ("kinstr", 1071)],
    "STKSimple": [("kpos", 2), ("kcross", 4), ("kenv", 11), ("kgain", 128)],
    "STKSitar": [],
    "STKStifKarp": [("kpos", 4), ("ksus", 11), ("kstretch", 1)],
    "STKTubeBell": [("kmod", 2), ("kcross", 4), ("klfo", 11), ("klfodepth", 1), ("kadsr", 128)],
    "STKVoicForm": [("kmix", 2), ("ksel", 4), ("klfo", 11), ("klfodepth", 1), ("kloud", 128)],
    "STKWhistle": [("kmod", 2), ("knoise", 4), ("kfipfreq", 11), ("kfipgain", 1), ("kvol", 128)],
    "STKWurley": [("kmod", 2), ("kcross", 4), ("klfo", 11), ("klfodepth", 1), ("kadsr", 128)],
}
