from __future__ import annotations

DEFAULT_PAD_COUNT = 8
MAX_SEQUENCER_STEPS = 128
PAUSE_BEAT_COUNTS = frozenset({1, 2, 4, 8, 16})
DEFAULT_TRACK_LENGTH_BEATS = 4
TRANSPORT_STEPS_PER_BEAT = 8
TRANSPORT_SUBUNITS_PER_STEP = 420
TRANSPORT_SUBUNITS_PER_BEAT = TRANSPORT_STEPS_PER_BEAT * TRANSPORT_SUBUNITS_PER_STEP
CONTROLLER_AUTOMATION_SUBUNIT_QUANTUM = 28
