import type { GuiLanguage } from "../../types";

const labels = {
  playback: ["Playback", "Wiedergabe", "Lecture", "Reproducción"],
  arranger: ["Arranger", "Arranger", "Arrangeur", "Arreglador"],
  live: ["Live", "Live", "Live", "En vivo"],
  active: ["Active", "Aktiv", "Actif", "Activo"],
  bypass: ["Bypass", "Durchleiten", "Contourner", "Paso directo"],
  mute: ["Mute", "Stumm", "Muet", "Silenciar"],
  hold: ["Hold", "Halten", "Maintien", "Retener"],
  off: ["Off", "Aus", "Désactivé", "Desactivado"],
  replace: ["Hold and replace", "Halten und ersetzen", "Maintenir et remplacer", "Retener y reemplazar"],
  toggle: ["Add/remove notes", "Noten hinzufügen/entfernen", "Ajouter/retirer des notes", "Añadir/quitar notas"],
  clear: ["Clear held notes", "Gehaltene Noten löschen", "Effacer les notes maintenues", "Borrar notas retenidas"],
  duration: ["Pad duration (beats)", "Pad-Dauer (Beats)", "Durée du pad (temps)", "Duración del pad (pulsos)"],
  cycle: ["Rhythm steps", "Rhythmusschritte", "Pas rythmiques", "Pasos rítmicos"],
  launch: ["Launch", "Starten", "Lancer", "Lanzar"],
  nextCycle: ["Next cycle", "Nächster Zyklus", "Cycle suivant", "Siguiente ciclo"],
  nextBar: ["Next master bar", "Nächster Master-Takt", "Prochaine mesure maître", "Siguiente compás maestro"],
  return: ["Return to arrangement", "Zurück zum Arrangement", "Revenir à l’arrangement", "Volver al arreglo"],
  cancel: ["Cancel launch", "Start abbrechen", "Annuler le lancement", "Cancelar lanzamiento"],
  editing: ["Editing", "Bearbeiten", "Édition", "Editando"],
  playing: ["Playing", "Spielt", "Lecture", "Reproduciendo"],
  queued: ["Queued", "Vorgemerkt", "En attente", "En cola"],
  next: ["Next note", "Nächste Note", "Note suivante", "Siguiente nota"],
  position: ["Chord-note position", "Akkordnotenposition", "Position dans l’accord", "Posición en el acorde"],
  rest: ["Rest", "Pause", "Silence", "Silencio"],
  tie: ["Tie", "Bindung", "Liaison", "Ligadura"],
  chord: ["Chord", "Akkord", "Accord", "Acorde"],
  step: ["Step", "Schritt", "Pas", "Paso"],
  previewNotes: ["Preview notes", "Notenvorschau", "Notes de l’aperçu", "Notas de vista previa"],
  scaleDegrees: ["Scale degrees", "Tonleiterstufen", "Degrés de la gamme", "Grados de la escala"],
  velocity: ["Velocity (%)", "Anschlagstärke (%)", "Vélocité (%)", "Velocidad (%)"],
  ratchets: ["Ratchets", "Mehrfachanschläge", "Répétitions rapides", "Repeticiones rápidas"],
  inherit: ["Use pad gate", "Pad-Gate verwenden", "Utiliser la durée du pad", "Usar duración del pad"],
  expression: ["Expression", "Ausdruck", "Expression", "Expresión"],
  harmony: ["Harmony", "Harmonie", "Harmonie", "Armonía"],
  advanced: ["Advanced timing", "Erweitertes Timing", "Timing avancé", "Temporización avanzada"],
  source: ["Follow source", "Quelle folgen", "Suivre la source", "Seguir origen"],
  custom: ["Custom", "Benutzerdefiniert", "Personnalisé", "Personalizado"],
  effective: ["Effective scale", "Wirksame Tonleiter", "Gamme effective", "Escala efectiva"],
  range: ["Full range", "Gesamter Bereich", "Toute la tessiture", "Rango completo"],
  octave: ["Octave by octave", "Oktave für Oktave", "Octave par octave", "Octava por octava"],
  traversal: ["Octave traversal", "Oktavfolge", "Parcours des octaves", "Recorrido de octavas"],
  rotation: ["Rotation", "Rotation", "Rotation", "Rotación"],
  advance: ["Advance through rests", "Bei Pausen weiterschalten", "Avancer pendant les silences", "Avanzar en silencios"],
  repeats: ["Note repeats", "Notenwiederholungen", "Répétitions de note", "Repeticiones de nota"],
  randomMode: ["Random variation", "Zufallsvariation", "Variation aléatoire", "Variación aleatoria"],
  repeat: ["Repeat variation", "Variation wiederholen", "Répéter la variation", "Repetir variación"],
  evolve: ["Evolve", "Weiterentwickeln", "Évoluer", "Evolucionar"],
  newVariation: ["New variation", "Neue Variation", "Nouvelle variation", "Nueva variación"],
  seed: ["Seed", "Startwert", "Graine", "Semilla"],
  modified: ["Modified", "Geändert", "Modifié", "Modificado"],
  update: ["Update preset", "Preset aktualisieren", "Actualiser le preset", "Actualizar preset"],
  saveAs: ["Save as preset", "Als Preset speichern", "Enregistrer un preset", "Guardar como preset"],
  missing: ["Target unavailable", "Ziel nicht verfügbar", "Destination indisponible", "Destino no disponible"],
  waiting_notes: ["Waiting for notes", "Wartet auf Noten", "En attente de notes", "Esperando notas"],
  waiting_arranger: ["Waiting for arranger", "Wartet auf Arranger", "En attente de l’arrangeur", "Esperando al arreglador"],
  stopped: ["Stopped", "Gestoppt", "Arrêté", "Detenido"],
  bypassed: ["Bypassed", "Durchgeleitet", "Contourné", "Paso directo"],
  muted: ["Muted", "Stumm", "Muet", "Silenciado"],
  pause: ["Arrangement pause", "Arrangement-Pause", "Silence de l’arrangement", "Silencio del arreglo"],
  hint: ["Select a pad to edit; use its play button to launch. Drag pads to copy. Space toggles a step; Delete inserts a rest; T ties; C plays the chord.",
    "Pad zum Bearbeiten wählen; mit seiner Play-Taste starten. Pads zum Kopieren ziehen. Leertaste schaltet einen Schritt um; Entf setzt eine Pause, T bindet, C spielt den Akkord.",
    "Sélectionnez un pad pour l’éditer ; lancez-le avec son bouton de lecture. Glissez les pads pour copier. Espace active un pas ; Suppr insère un silence ; T lie ; C joue l’accord.",
    "Seleccione un pad para editar; use su botón de reproducción para lanzarlo. Arrastre pads para copiar. Espacio alterna un paso; Supr inserta silencio; T liga; C toca el acorde."],
} as const;

export function arpeggiatorCopy(language: GuiLanguage): Record<keyof typeof labels, string> {
  const index = { english: 0, german: 1, french: 2, spanish: 3 }[language];
  return Object.fromEntries(Object.entries(labels).map(([key, values]) => [key, values[index]])) as Record<keyof typeof labels, string>;
}
