import type { GuiLanguage } from "../types";

export const arrangementHelp: Record<GuiLanguage, string> = {
  english: `## Song order and reusable phrases

Pads are named 1–8 in the arranger and #1–#8 in sequencers. Defaults are green pads, red groups, violet supergroups and dark rests. Numbers identify pad slots, not duration. Right-click a musical occurrence or palette entry to Set colour or Reset colour. A custom colour is saved for that definition in this lane and shared by its palette and occurrences; sequencer colours stay unchanged.

The triangle beside a track title opens or closes its editor. Click anywhere in an occurrence to select it and open the lane; Cmd/Ctrl-click toggles selection. Empty timeline space clears highlights and sets Position without changing expansion. Playback settings has its own disclosure. Closing preserves editing context; New/Load/Import resets it. Melodic and drummer sequencers provide an upper-right pattern workspace; controller and arpeggiator editors retain Patterns and phrases.

Mute/Solo affects this lane only, even when lanes share an instrument. Multiple solos are allowed; explicit mute wins. Dashed amber Mute means suppressed by another Solo. Muted lanes keep advancing; unmute resumes future events at the current position. Existing notes release normally and CC values stay at their last applied value until another update. Drummer rows act together. Solo preserves needed arpeggiator inputs and processing; explicit mute still wins. External MIDI and independent Live arpeggiators are outside solo selection. Lane controls survive engine restart but reset on New/Load/Import or reload and are never saved or exported. Mixer controls remain independent.

Only the multitrack arranger edits song order. The palette hides pattern pads containing only rest steps and keeps their original numbers. Drag pads, groups, supergroups or rests from the wrapping palette beside Position (master beats). At a boundary, dropping inserts and shifts later material on this lane. Inside a rest, musical material must fit. Beyond the end, pauses fill the gap. Occupied musical destinations are rejected. Drag a contiguous selection to move it, leaving silence at its source. The preview shows the resolved position and duration. There are no placement toolbar buttons or number-key placement shortcuts. Range copy, paste and duplicate use the context menu and keyboard.

Drag the top beat ruler to select a section across all lanes, including collapsed and muted ones. Drag empty timeline background or Shift-drag over elements for a rectangle across selected lanes. Cyan highlights include silence and show duration and lane count. Boundaries expand outwards to preserve whole pads, groups and supergroups; rests split only at whole local beats. Click the top ruler for an edit position; it does not seek or change the separate bottom loop ruler. Shift+arrows extends the selection. Right-click inside it preserves it; right-click elsewhere chooses a destination.

Copy range: Cmd/Ctrl+C. Paste — overwrite: Cmd/Ctrl+V, replacing the full interval on copied lanes without shifting later material. Paste — insert time, all lanes: Cmd/Ctrl+Shift+V, shifting all later material together and inserting silence on unselected lanes where needed. Duplicate — insert time, all lanes: Cmd/Ctrl+Shift+D, repeating immediately after the selection; A–B becomes A–A–B. Context menus also offer insertion or duplication on copied/selected lanes only. The new copy stays selected. Alt/Option-drag a selected occurrence copies the range; add Shift to insert time across all lanes. The preview names the mode, position and affected lanes; red explains an invalid destination. Ordinary occurrence dragging exits range selection. Escape, pointer cancellation or focus loss cancels a gesture. Shortcuts ignore text fields and controls; Delete remains an occurrence action.

Copies keep their lane assignments and reuse pads and definitions, including colours and internal/trailing silence. Create variation separates definitions; create a pad variation for independent notes or curves. No automatic repetitions are expanded. Musical elements cannot be split at the destination; invalid boundaries, local-beat timing, changed definitions/durations or sequence limits reject the entire operation. Range edits retain Playback source, independent Manual pads, transport and loop positions and follow the normal live-edit preparation rules. Cmd/Ctrl+Z undoes a range edit; Cmd/Ctrl+Shift+Z (also Ctrl+Y) redoes it. Up to 50 range edits, selection and clipboard survive collapse and view switches; New/Load/Import resets them, and save/export excludes them. Other sequence, definition, duration, beat-ratio or lane-membership edits clear range history, including while closed. Notes, colours, mixer and runtime updates preserve it. Changed definitions or lengths require copying again.

Right-click for editing actions; Shift+F10 opens the same menu from the keyboard and Escape dismisses it. Double-click a pad to open its sequencer editor. Group at least two contiguous pads/rests; a Supergroup may also contain groups. Ungroup expands one level and retains the definition. Rearrange, then regroup as a new definition or explicitly update an existing one. Updating affects every reference and duration changes shift following material. Create variation makes an independent copy, using a free slot for pads. Unused definitions remain available; only saved arrangement/phrase references block palette deletion. Temporary workspace references expand into their saved contents. Empty drafts cannot be placed or auditioned. Delete/Backspace leaves equivalent silence; Shift+Delete or Remove and close gap closes time. Resize rests by their right edge or the Duration menu. Fit includes trailing rests.

Playback source selects Arrangement or Manual pads. At end selects Stop track or Repeat track sequence in the arranger. New devices stop; imported repeat settings remain. Empty lanes are manual; adding their first item selects Arrangement. Loop selected range is a separate shared loop. Play runs from the current cursor to the song end, including trailing rests, then stops there. A marked loop range repeats only that range. Repeating lanes stay within these bounds.

Hold a speaker for 250 ms to preview a pad or phrase from its first token. While the arranger runs, preview starts at the next lane cycle boundary. While stopped, it starts at the next available audio block without moving the song cursor. Play or Stop is highlighted to show the arranger’s current state. Releasing before the boundary cancels the queued preview. Short clicks do nothing. Preview repeats while held; releasing restores the lane’s previous arrangement, manual playback or sequencer audition at the current shared-clock position. Previously stopped lanes stay stopped. Other tracks continue. Space/Enter supports the same hold/release gesture. Cancellation, focus loss, collapse and navigation end the preview. Seeks and loops restart held previews at their first token; song boundaries remain authoritative.

Controller/arpeggiator Audition keeps its existing boundary-based behavior: it repeats until Stop audition or Return to arrangement, with return at the next boundary. Arranger Play clears auditions/previews, starts Arrangement lanes and preserves playing Manual pads sequencers. Stop clears auditions/previews and stops Arrangement lanes while preserving other independently started manual tracks. Live arpeggiators remain independent. Preview and audition state is never saved or exported; musical edits and custom colours save normally.`,
  german: `## Songfolge und wiederverwendbare Phrasen

Pads heißen im Arranger 1–8 und in Sequencern #1–#8. Standardfarben sind Grün für Pads, Rot für Gruppen, Violett für Supergruppen und Dunkel für Pausen. Nummern bezeichnen Pad-Plätze, keine Dauer. Rechtsklick auf ein musikalisches Vorkommen oder einen Paletteneintrag bietet Farbe festlegen und Farbe zurücksetzen. Eine eigene Farbe wird für die Definition dieser Spur gespeichert und gilt für Palette und alle Vorkommen; Sequencer-Farben bleiben unverändert.

Das Dreieck neben dem Spurnamen öffnet oder schließt den Editor. Ein Klick irgendwo im Element wählt es und öffnet die Spur; Cmd/Strg-Klick schaltet die Auswahl um. Freie Timeline-Fläche hebt Markierungen auf und setzt Position, ohne die Spur zu öffnen oder zu schließen. Wiedergabeeinstellungen haben einen eigenen Bereich. Schließen erhält den Bearbeitungszustand; Neu/Laden/Import setzt ihn zurück. Melodie- und Drummer-Sequencer haben oben rechts eine Pattern-Arbeitsfläche; Controller und Arpeggiatoren behalten Patterns und Phrasen.

Mute/Solo wirkt nur auf diese Spur, auch bei gemeinsamem Instrument. Mehrere Solos sind möglich; explizites Mute hat Vorrang. Ein gestricheltes bernsteinfarbenes Mute zeigt Unterdrückung durch ein anderes Solo. Stumme Spuren laufen zeitlich weiter und steigen bei Freigabe an der aktuellen Position wieder ein. Klingende Noten klingen normal aus; CC-Werte bleiben bis zur nächsten Aktualisierung bestehen. Drum-Zeilen werden gemeinsam geschaltet. Solo erhält benötigte Arpeggiator-Eingänge und Verarbeitung; explizites Mute gilt weiter. Externes MIDI und unabhängige Live-Arpeggiatoren bleiben außerhalb der Solo-Auswahl. Spurkontrollen überstehen einen Engine-Neustart, werden bei Neu/Laden/Import oder Browser-Neuladen zurückgesetzt und nie gespeichert oder exportiert. Mixer-Kontrollen bleiben unabhängig.

Nur der Multitrack Arranger bearbeitet die Songfolge. Die Palette blendet Pattern-Pads mit ausschließlich Pausenschritten aus und behält ihre ursprünglichen Nummern. Pads, Gruppen, Supergruppen und Pausen aus der umbrechenden Palette neben Position (Master-Beats) ziehen. An Elementgrenzen fügt Ablegen ein und verschiebt Folgematerial dieser Spur. In eine Pause muss musikalisches Material hineinpassen. Hinter dem Ende füllen Pausen den Abstand. Belegte musikalische Ziele werden abgelehnt. Zusammenhängende Auswahl verschieben lässt Stille am Ursprung. Die Vorschau zeigt Zielposition und Dauer. Es gibt keine Platzierungsschaltflächen oder Platzierung per Zifferntaste. Bereichskopien, Einfügen und Duplizieren sind über Kontextmenü und Tastatur verfügbar.

Das obere Beat-Lineal ziehen, um einen Bereich über alle Spuren einschließlich eingeklappter und stummer Spuren auszuwählen. Für einzelne Spuren ein Rechteck im freien Zeitbereich oder mit Umschalt über Elementen ziehen. Die cyanfarbene Markierung umfasst Pausen und zeigt Dauer und Spuranzahl. Grenzen werden nach außen erweitert, damit Pads, Gruppen und Supergruppen vollständig bleiben; Pausen können an ganzen lokalen Beats geteilt werden. Ein Klick im oberen Lineal setzt die Bearbeitungsposition, ohne Wiedergabe oder unteres Loop-Lineal zu ändern. Umschalt+Pfeiltasten erweitert die Auswahl. Rechtsklick innerhalb behält sie bei; außerhalb wird das Ziel gewählt.

Cmd/Ctrl+C kopiert den Bereich. Cmd/Ctrl+V überschreibt das gesamte Zielintervall auf den kopierten Spuren, ohne Folgematerial zu verschieben. Cmd/Ctrl+Umschalt+V fügt Zeit auf allen Spuren ein und verschiebt deren Folgematerial gemeinsam; nicht gewählte Spuren erhalten bei Bedarf Pausen. Cmd/Ctrl+Umschalt+D dupliziert direkt nach der Auswahl mit Zeiteinfügung auf allen Spuren: A–B wird A–A–B. Das Kontextmenü bietet außerdem Einfügen oder Duplizieren nur auf kopierten/gewählten Spuren. Die Kopie bleibt ausgewählt. Alt/Option-Ziehen eines ausgewählten Vorkommens kopiert den Bereich; zusätzlich Umschalt fügt Zeit auf allen Spuren ein. Die Vorschau nennt Modus, Position und Spuren; Rot erklärt ungültige Ziele. Normales Ziehen eines Vorkommens beendet die Bereichsauswahl. Escape, Zeigerabbruch oder Fokusverlust bricht Gesten ab. Tastenkürzel gelten außerhalb von Textfeldern und Bedienelementen; Löschen bleibt eine Vorkommensaktion.

Kopien behalten ihre Spuren und verwenden dieselben Pads und Definitionen einschließlich Farben sowie interner und abschließender Pausen. Variation erstellen trennt Definitionen; für unabhängige Noten oder Kurven auch das Pad variieren. Automatische Wiederholungen werden nicht materialisiert. Musikalische Elemente können am Ziel nicht geteilt werden. Ungültige Grenzen, lokale Beat-Dauern, geänderte Definitionen/Längen oder Sequenzlimits verhindern die gesamte Änderung. Wiedergabequelle, unabhängige manuelle Pads, Transport und Loop-Positionen bleiben erhalten; Live-Änderungen nutzen die normale Vorbereitung. Cmd/Ctrl+Z macht eine Bereichsänderung rückgängig, Cmd/Ctrl+Umschalt+Z oder Ctrl+Y stellt sie wieder her. Bis zu 50 Bereichsänderungen, Auswahl und Zwischenablage überstehen Einklappen und Ansichtswechsel; Neu/Laden/Import setzt sie zurück, Speichern/Export schließt sie aus. Andere Änderungen an Sequenz, Definitionen, Pad-Längen, Beat-Verhältnissen oder Spuren verwerfen die Bereichshistorie, auch bei geschlossenem Arranger. Noten, Farben, Mixer und Laufzeitaktualisierungen erhalten sie. Nach geänderten Definitionen oder Längen erneut kopieren.

Rechtsklick öffnet Bearbeitungsaktionen; per Tastatur öffnet Umschalt+F10 dasselbe Menü, Escape schließt es. Doppelklick auf ein Pad öffnet seinen Sequencer-Editor. Mindestens zwei benachbarte Pads/Pausen bilden eine Gruppe; Supergruppen dürfen auch Gruppen enthalten. Gruppierung aufheben erweitert eine Ebene und behält die Definition. Neu anordnen und danach als neue Definition gruppieren oder eine bestehende ausdrücklich aktualisieren. Aktualisieren betrifft alle Referenzen; Längenänderungen verschieben Folgematerial. Variation erstellen erzeugt eine unabhängige Kopie, bei Pads in einem freien Platz. Unbenutzte Definitionen bleiben erhalten; nur gespeicherte Arrangement-/Phrasenverweise sperren das Löschen aus der Palette. Temporäre Arbeitsflächenverweise werden in ihre gespeicherten Inhalte aufgelöst. Leere Entwürfe lassen sich nicht platzieren oder vorhören. Delete/Backspace lässt gleich lange Stille; Umschalt+Delete oder Entfernen und Lücke schließen verkürzt die Zeit. Pausen am rechten Rand oder im Dauer-Menü ändern. Einpassen berücksichtigt Endpausen.

Wiedergabequelle wählt Arrangement oder Manuelle Pads. Am Ende bietet im Arranger Spur stoppen oder Spursequenz wiederholen. Neue Geräte stoppen; importierte Einstellungen bleiben erhalten. Leere Spuren sind manuell; das erste Element aktiviert Arrangement. Ausgewählten Bereich wiederholen ist der gemeinsame Transport-Loop. Play spielt ab der aktuellen Position bis zum Songende einschließlich abschließender Pausen und stoppt dort. Ein markierter Loop-Bereich wird wiederholt. Wiederholte Spuren bleiben innerhalb dieser Grenzen.

Lautsprechersymbol 250 ms halten: Pad oder Phrase startet beim ersten Element. Bei laufendem Arranger beginnt die Vorschau an der nächsten Zyklusgrenze der Spur. Im Stopp beginnt sie im nächsten verfügbaren Audioblock, ohne den Song-Cursor zu bewegen. Play oder Stopp wird entsprechend dem Arranger-Zustand hervorgehoben. Loslassen vor der Grenze bricht die vorgemerkte Vorschau ab. Kurze Klicks bewirken nichts. Während des Haltens wird wiederholt; Loslassen stellt das vorherige Arrangement, manuelle Spiel oder Sequencer-Vorhören an der aktuellen gemeinsamen Zeitposition wieder her. Zuvor gestoppte Spuren bleiben gestoppt. Andere Spuren laufen weiter. Leertaste/Enter unterstützt dasselbe Halten und Loslassen. Abbruch, Fokusverlust, Einklappen und Navigation beenden die Vorschau. Positionswechsel und Loops starten gehaltene Vorschauen beim ersten Element; Songgrenzen bleiben maßgeblich.

Controller-/Arpeggiator-Vorhören bleibt grenzbasiert: Es wiederholt bis Vorhören stoppen oder Zurück zum Arrangement; die Rückkehr erfolgt an der nächsten Grenze. Arranger-Play beendet Vorhören/Vorschauen, startet Arrangement-Spuren und lässt laufende manuelle Sequencer weiterspielen. Stop beendet Vorhören/Vorschauen und Arrangement-Spuren; andere unabhängig gestartete manuelle Spuren laufen weiter. Live-Arpeggiatoren bleiben unabhängig. Vorhörzustände werden nie gespeichert oder exportiert; musikalische Änderungen und eigene Farben werden normal gespeichert.`,
  french: `## Ordre du morceau et phrases réutilisables

Les pads sont nommés 1–8 dans l’arrangeur et #1–#8 dans les séquenceurs. Couleurs par défaut : pads verts, groupes rouges, supergroupes violets et silences sombres. Les numéros désignent des emplacements, pas des durées. Un clic droit sur une occurrence musicale ou une entrée de palette propose Définir la couleur et Réinitialiser la couleur. La couleur est sauvegardée pour cette définition de piste et partagée par sa palette et toutes ses occurrences ; les couleurs du séquenceur restent inchangées.

Le triangle près du nom ouvre ou ferme l’éditeur. Cliquez n’importe où dans une occurrence pour la sélectionner et ouvrir la piste ; Cmd/Ctrl-clic bascule la sélection. Cliquer un espace vide efface les sélections et règle Position sans changer l’ouverture. Réglages de lecture possède son propre volet. Fermer conserve le contexte ; Nouveau/Charger/Importer le réinitialise. Les séquenceurs mélodiques et de batterie disposent d’un atelier en haut à droite ; contrôleurs et arpégiateurs gardent Motifs et phrases.

Muet/Solo agit uniquement sur cette piste, même si plusieurs pistes partagent un instrument. Plusieurs solos sont possibles ; Muet explicite prime. Un bouton Muet ambre en pointillés indique l’exclusion par un autre Solo. Les pistes muettes avancent toujours ; leur réactivation reprend les événements futurs à la position actuelle. Les notes en cours se terminent normalement ; les valeurs CC restent jusqu’à une nouvelle mise à jour. Les lignes de batterie changent ensemble. Solo conserve les entrées et traitements d’arpégiateur nécessaires ; Muet explicite reste prioritaire. Le MIDI externe et les arpégiateurs Live indépendants restent hors de la sélection Solo. Ces contrôles survivent au redémarrage du moteur, se réinitialisent sur Nouveau/Charger/Importer ou rechargement et ne sont jamais sauvegardés ni exportés. Le mixeur reste indépendant.

Seul l’arrangeur multipiste modifie l’ordre du morceau. La palette masque les pads ne contenant que des pas de silence et conserve leurs numéros d’origine. Glissez pads, groupes, supergroupes ou silences depuis la palette à côté de Position (temps maîtres), avec retour à la ligne. À une limite, le dépôt insère et décale la suite de cette piste. Dans un silence, le contenu musical doit tenir. Après la fin, des silences comblent l’écart. Les destinations musicales occupées sont refusées. Déplacer une sélection contiguë laisse du silence à sa source. L’aperçu montre la position et la durée retenues. Il n’y a ni boutons de placement ni placement par touches numériques. Copier, coller et dupliquer des plages sont disponibles dans le menu contextuel et au clavier.

Glissez sur la règle supérieure pour sélectionner une plage sur toutes les pistes, même repliées ou muettes. Pour certaines pistes, tracez un rectangle depuis le fond vide ou avec Maj sur les éléments. La sélection cyan comprend les silences et indique durée et nombre de pistes. Ses limites s’étendent vers l’extérieur pour préserver pads, groupes et supergroupes entiers ; seuls les silences se divisent en temps locaux entiers. Cliquer sur la règle supérieure définit la position d’édition sans déplacer la lecture ni modifier la règle de boucle inférieure. Maj+flèches étend la sélection. Un clic droit à l’intérieur la préserve ; ailleurs il choisit la destination.

Cmd/Ctrl+C copie la plage. Cmd/Ctrl+V écrase tout l’intervalle cible sur les pistes copiées sans déplacer la suite. Cmd/Ctrl+Maj+V insère du temps sur toutes les pistes, décale leur suite ensemble et ajoute du silence aux pistes non sélectionnées si nécessaire. Cmd/Ctrl+Maj+D duplique immédiatement après la sélection en insérant du temps partout : A–B devient A–A–B. Le menu propose aussi l’insertion ou la duplication sur les seules pistes copiées/sélectionnées. La copie reste sélectionnée. Alt/Option-glisser une occurrence sélectionnée copie la plage ; ajouter Maj insère du temps sur toutes les pistes. L’aperçu indique mode, position et pistes ; le rouge explique les destinations invalides. Un déplacement ordinaire d’occurrence quitte la sélection de plage. Échap, annulation du pointeur ou perte de focus annule le geste. Les raccourcis ignorent champs de texte et contrôles ; Supprimer reste une action d’occurrence.

Les copies gardent leurs pistes et réutilisent pads et définitions, couleurs et silences internes/finaux compris. Créer une variation sépare une définition ; pour des notes ou courbes indépendantes, varier aussi le pad. Les répétitions automatiques ne sont pas développées. Les éléments musicaux ne peuvent pas être divisés à destination. Limites invalides, durées locales, définitions/durées modifiées ou limites de séquence bloquent toute l’opération. Source de lecture, pads manuels indépendants, transport et boucle sont conservés ; les éditions en lecture suivent la préparation normale. Cmd/Ctrl+Z annule une édition de plage ; Cmd/Ctrl+Maj+Z ou Ctrl+Y la rétablit. Jusqu’à 50 éditions, sélection et presse-papiers survivent au repli et aux changements de vue ; Nouveau/Charger/Importer les réinitialise, sauvegarde/export les excluent. D’autres modifications des séquences, définitions, durées, rapports de temps ou pistes effacent cet historique, même lorsque l’arrangeur est fermé. Notes, couleurs, mixeur et mises à jour de lecture le préservent. Après changement de définitions ou durées, recopier la plage.

Clic droit pour les actions ; Maj+F10 ouvre le même menu au clavier et Échap le ferme. Double-cliquez un pad pour ouvrir son séquenceur. Un groupe requiert au moins deux pads/silences contigus ; un supergroupe accepte aussi des groupes. Dégrouper développe un niveau et conserve la définition. Réorganisez puis regroupez en nouvelle définition ou mettez explicitement à jour une définition existante. Une mise à jour affecte toutes les références ; changer la durée décale la suite. Créer une variation produit une copie indépendante, dans un emplacement libre pour un pad. Les définitions inutilisées restent disponibles ; seules les références enregistrées dans un arrangement ou une phrase bloquent leur suppression. Les références temporaires sont développées en leur contenu enregistré. Un brouillon vide ne peut être placé ni écouté. Suppr/Retour arrière laisse un silence équivalent ; Maj+Suppr ou Supprimer et fermer l’espace retire la durée. Redimensionnez un silence par son bord droit ou le menu Durée. Ajuster inclut les silences finaux.

Source de lecture choisit Arrangement ou Pads manuels. À la fin choisit Arrêter la piste ou Répéter la séquence dans l’arrangeur. Les nouveaux appareils s’arrêtent ; les réglages importés restent intacts. Une piste vide est manuelle ; son premier élément active Arrangement. Boucler la plage sélectionnée commande la boucle commune. Play lit depuis la position actuelle jusqu’à la fin du morceau, silences finaux inclus, puis s’y arrête. Une plage de boucle marquée se répète seule. Les pistes répétées restent dans ces limites.

Maintenez un haut-parleur 250 ms pour écouter le pad ou la phrase depuis son début. Pendant la lecture de l’arrangeur, l’aperçu commence à la prochaine limite de cycle de la piste. À l’arrêt, il commence au prochain bloc audio disponible sans déplacer le curseur du morceau. Lecture ou Arrêt est mis en évidence selon l’état de l’arrangeur. Relâcher avant la limite annule l’aperçu en attente. Un clic bref ne fait rien. L’écoute se répète pendant le maintien ; relâcher restaure l’arrangement, le jeu manuel ou l’écoute du séquenceur précédent à la position actuelle de l’horloge commune. Une piste auparavant arrêtée reste arrêtée. Les autres continuent. Espace/Entrée permet le même maintien au clavier. Annulation, perte de focus, fermeture et navigation terminent l’aperçu. Déplacements et boucles reprennent les aperçus maintenus au premier élément ; les limites du morceau restent prioritaires.

L’écoute des contrôleurs/arpégiateurs conserve son fonctionnement aux limites : elle répète jusqu’à Arrêter l’écoute ou Retour à l’arrangement, avec retour à la prochaine limite. Play efface écoutes et aperçus, lance les pistes Arrangement et préserve les séquenceurs manuels en cours. Stop efface écoutes et aperçus et arrête les pistes Arrangement, tout en préservant les autres pistes manuelles lancées séparément. Les arpégiateurs Live restent indépendants. Les états d’écoute ne sont jamais sauvegardés ni exportés ; les modifications musicales et couleurs personnalisées le sont.`,
  spanish: `## Orden del tema y frases reutilizables

Los pads se llaman 1–8 en el arreglador y #1–#8 en los secuenciadores. Colores predeterminados: pads verdes, grupos rojos, supergrupos violetas y silencios oscuros. Los números identifican espacios, no duraciones. El clic derecho en una aparición musical o entrada de paleta ofrece Establecer color y Restablecer color. El color se guarda para esa definición de pista y lo comparten su paleta y todas sus apariciones; los colores del secuenciador no cambian.

El triángulo junto al nombre abre o cierra el editor. Pulsa cualquier zona de una aparición para seleccionarla y abrir la pista; Cmd/Ctrl-clic alterna la selección. Un espacio vacío borra las selecciones y establece Posición sin cambiar la apertura. Ajustes de reproducción tiene su propio panel. Cerrar conserva el contexto; Nuevo/Cargar/Importar lo restablece. Los secuenciadores melódicos y de batería tienen un taller arriba a la derecha; controladores y arpegiadores conservan Patrones y frases.

Mute/Solo afecta solo a esta pista, aunque varias compartan instrumento. Se permiten varios solos; Mute explícito tiene prioridad. Mute ámbar discontinuo indica exclusión por otro Solo. Las pistas silenciadas siguen avanzando; reactivarlas retoma eventos futuros en la posición actual. Las notas activas terminan normalmente; los valores CC permanecen hasta otra actualización. Las filas de batería cambian juntas. Solo conserva entradas y procesamiento de arpegiador necesarios; Mute explícito sigue teniendo prioridad. El MIDI externo y los arpegiadores Live independientes quedan fuera de Solo. Estos controles sobreviven al reinicio del motor, se restablecen con Nuevo/Cargar/Importar o recarga y nunca se guardan ni exportan. El mezclador sigue independiente.

Solo el arreglador multipista edita el orden del tema. La paleta oculta los pads que solo contienen pasos de silencio y conserva sus números originales. Arrastra pads, grupos, supergrupos o silencios desde la paleta con ajuste de línea junto a Posición (pulsos maestros). En un límite, soltar inserta y desplaza lo siguiente en esa pista. Dentro de un silencio, el material musical debe caber. Tras el final, se añaden silencios para cubrir el hueco. Se rechazan destinos musicales ocupados. Mover una selección contigua deja silencio en su origen. La vista previa muestra la posición y duración resueltas. No hay botones de colocación ni colocación mediante teclas numéricas. Copiar, pegar y duplicar intervalos está disponible en el menú contextual y el teclado.

Arrastra sobre la regla superior para seleccionar un intervalo en todas las pistas, incluidas las plegadas o silenciadas. Para algunas pistas, dibuja un rectángulo desde el fondo vacío o con Mayús sobre elementos. La selección cian incluye silencios y muestra duración y número de pistas. Los límites se amplían hacia fuera para conservar pads, grupos y supergrupos completos; los silencios solo se dividen en pulsos locales enteros. Un clic en la regla superior fija la posición de edición sin mover la reproducción ni cambiar la regla de bucle inferior. Mayús+flechas amplía la selección. El clic derecho dentro la conserva; fuera elige el destino.

Cmd/Ctrl+C copia el intervalo. Cmd/Ctrl+V sobrescribe todo el intervalo de destino en las pistas copiadas sin desplazar lo posterior. Cmd/Ctrl+Mayús+V inserta tiempo en todas las pistas, desplaza juntas las partes posteriores e introduce silencio en las pistas no seleccionadas cuando hace falta. Cmd/Ctrl+Mayús+D duplica justo después de la selección insertando tiempo en todas las pistas: A–B pasa a A–A–B. El menú también permite insertar o duplicar solo en las pistas copiadas/seleccionadas. La copia queda seleccionada. Alt/Option-arrastrar una aparición seleccionada copia el intervalo; añade Mayús para insertar tiempo en todas las pistas. La vista previa indica modo, posición y pistas; el rojo explica destinos no válidos. Arrastrar una aparición normalmente sale de la selección de intervalo. Escape, cancelación del puntero o pérdida de foco cancela el gesto. Los atajos ignoran campos de texto y controles; Eliminar sigue siendo una acción de aparición.

Las copias conservan sus pistas y reutilizan pads y definiciones, incluidos colores y silencios internos/finales. Crear variación separa definiciones; para notas o curvas independientes, crea también una variación del pad. Las repeticiones automáticas no se expanden. Los elementos musicales no se dividen en el destino. Límites no válidos, duraciones locales, definiciones/duraciones modificadas o límites de secuencia rechazan toda la operación. Se conservan fuente de reproducción, pads manuales independientes, transporte y bucle; los cambios durante la reproducción siguen la preparación habitual. Cmd/Ctrl+Z deshace una edición de intervalo; Cmd/Ctrl+Mayús+Z o Ctrl+Y la rehace. Hasta 50 ediciones, selección y portapapeles sobreviven al plegado y a cambios de vista; Nuevo/Cargar/Importar los reinicia, guardar/exportar los excluye. Otros cambios de secuencias, definiciones, duraciones, relaciones de pulsos o pistas borran este historial, incluso con el arreglador cerrado. Notas, colores, mezclador y actualizaciones de reproducción lo conservan. Si cambian definiciones o duraciones, vuelve a copiar.

Clic derecho para las acciones; Mayús+F10 abre el mismo menú con el teclado y Escape lo cierra. Doble clic en un pad abre su secuenciador. Un grupo requiere al menos dos pads/silencios contiguos; un supergrupo también admite grupos. Desagrupar expande un nivel y conserva la definición. Reorganiza y vuelve a agrupar como definición nueva o actualiza explícitamente una existente. Actualizar afecta todas las referencias; cambiar la duración desplaza lo siguiente. Crear variación genera una copia independiente, en un espacio libre si es un pad. Las definiciones sin usar se conservan; solo las referencias guardadas en un arreglo o frase bloquean la eliminación. Las referencias temporales se expanden en su contenido guardado. Los borradores vacíos no pueden colocarse ni escucharse. Supr/Retroceso deja silencio equivalente; Mayús+Supr o Eliminar y cerrar hueco retira el tiempo. Ajusta silencios desde el borde derecho o el menú Duración. Ajustar incluye los silencios finales.

Fuente de reproducción elige Arreglo o Pads manuales. Al finalizar elige Detener pista o Repetir secuencia en el arreglador. Los dispositivos nuevos se detienen; se conservan los ajustes importados. Una pista vacía es manual; su primer elemento activa Arreglo. Repetir intervalo seleccionado es el bucle compartido. Play reproduce desde la posición actual hasta el final del tema, incluidos los silencios finales, y se detiene allí. Si hay un intervalo de bucle marcado, repite solo ese intervalo. Las pistas repetidas respetan estos límites.

Mantén un altavoz 250 ms para escuchar el pad o frase desde su inicio. Durante la reproducción del arreglador, comienza en el siguiente límite de ciclo de la pista. Si está detenido, comienza en el siguiente bloque de audio disponible sin mover el cursor del tema. Reproducir o Detener se resalta según el estado del arreglador. Soltar antes del límite cancela la escucha pendiente. Un clic breve no hace nada. Se repite mientras mantienes pulsado; soltar restaura el arreglo, reproducción manual o escucha previa del secuenciador en la posición actual del reloj compartido. Las pistas antes detenidas siguen detenidas. Las demás continúan. Espacio/Intro ofrece el mismo gesto con el teclado. Cancelación, pérdida de foco, cierre y navegación terminan la escucha. Saltos y bucles reinician las escuchas mantenidas desde el primer elemento; los límites del tema siguen vigentes.

La escucha de controladores/arpegiadores mantiene su funcionamiento por límites: repite hasta Detener escucha o Volver al arreglo, con retorno en el siguiente límite. Play borra escuchas y vistas previas, inicia pistas Arreglo y conserva los secuenciadores manuales en marcha. Stop borra escuchas y vistas previas y detiene pistas Arreglo, conservando las otras pistas manuales iniciadas aparte. Los arpegiadores Live siguen independientes. Los estados de escucha nunca se guardan ni exportan; los cambios musicales y colores personalizados sí.`
};
