import type { GuiLanguage } from "../types";

export const arrangementHelp: Record<GuiLanguage, string> = {
  english: `## Song order and reusable phrases

The triangle beside a track title opens or closes its editor. Clicking an occurrence opens it; clicking empty timeline space clears highlights without changing expansion. Patterns and phrases and Playback settings have their own disclosures, collapsed by default. Closing retains editing context; New/Load/Import resets the layout.

Mute/Solo affects this lane only, even when lanes share an instrument. Multiple solos are allowed; explicit mute wins. Dashed amber Mute means suppressed by another Solo. Muted lanes keep advancing; unmute resumes future events at the current position. Existing notes release normally and CC values stay at their last applied value until another update. Drummer rows act together. Solo preserves needed arpeggiator inputs and processing; explicit mute still wins. External MIDI and independent Live arpeggiators are outside solo selection. Lane controls survive engine restart but reset on New/Load/Import or reload and are never saved or exported. Mixer controls remain independent.

The multitrack arranger is the only song-order editor. Select a lane to use its pad, group, supergroup and rest palette. Drag or Add into available silence; occupied destinations are rejected. Insert and shift later items works at boundaries on this lane only. Delete/Backspace leaves equal-duration silence; Remove and close gap closes time. Rest-edge drags and Duration edits shift later items. Fit includes trailing rests.

Click a pad to edit it; selection never launches playback. Playing, Queued and Auditioning are separate from Editing. Sequencers and arranger Edit share the same definition library. Changes affect all occurrences; length changes shift subsequent material. Unused and empty draft definitions are retained. Empty drafts cannot be placed or auditioned; referenced definitions cannot be emptied or deleted. The library shows their uses. Duplicate occurrence retains a reference; Create variation copies the definition or uses an available pad slot.

Playback source selects Arrangement or Manual pads. At end selects Stop track or Repeat track sequence in the arranger. New devices stop; imported repeat settings remain. Empty lanes are manual; adding their first item selects Arrangement. Loop selected range is a separate shared loop.

Audition temporarily repeats a pad or phrase on this track, beginning at its next pad/rest boundary. Other tracks continue. Return to arrangement takes effect at the next boundary at the current song position, including rests and ended tracks. Stop audition stops this track without restarting the song. With transport stopped, audition starts only this track. Seeks and loops restart auditions from their first token. Queued audition changes take effect at the seek or loop destination. Song boundaries remain authoritative.

Arranger Play clears auditions, starts Arrangement lanes and stops Manual pads sequencers. Stop clears auditions and stops Arrangement lanes while preserving independently started manual tracks. Live arpeggiators retain their existing behavior. Audition state is never saved or exported; musical edits still save normally.`,
  german: `## Songfolge und wiederverwendbare Phrasen

Das Dreieck neben dem Spurnamen öffnet oder schließt den Editor. Ein Vorkommen öffnet ihn; ein Klick in freie Timeline-Fläche hebt Markierungen auf, ohne den Editor zu öffnen oder zu schließen. Patterns und Phrasen sowie Wiedergabeeinstellungen haben eigene, anfangs geschlossene Bereiche. Der Bearbeitungszustand bleibt beim Schließen erhalten; Neu/Laden/Import setzt das Layout zurück.

Mute/Solo wirkt nur auf diese Spur, auch bei gemeinsamem Instrument. Mehrere Solos sind möglich; explizites Mute hat Vorrang. Ein gestricheltes bernsteinfarbenes Mute zeigt Unterdrückung durch ein anderes Solo. Stumme Spuren laufen zeitlich weiter und steigen bei Freigabe an der aktuellen Position wieder ein. Klingende Noten klingen normal aus; CC-Werte bleiben bis zur nächsten Aktualisierung bestehen. Drum-Zeilen werden gemeinsam geschaltet. Solo erhält benötigte Arpeggiator-Eingänge und Verarbeitung; explizites Mute gilt weiter. Externes MIDI und unabhängige Live-Arpeggiatoren bleiben außerhalb der Solo-Auswahl. Spurkontrollen überstehen einen Engine-Neustart, werden bei Neu/Laden/Import oder Browser-Neuladen zurückgesetzt und nie gespeichert oder exportiert. Mixer-Kontrollen bleiben unabhängig.

Nur der Multitrack Arranger bearbeitet die Songfolge. Eine Spur wählen und Pads, Gruppen, Supergruppen oder Pausen aus der Palette ziehen oder hinzufügen. Belegte Ziele werden abgelehnt. Einfügen und Folgeelemente verschieben funktioniert an Elementgrenzen nur auf dieser Spur. Delete/Backspace lässt gleich lange Stille; Entfernen und Lücke schließen verkürzt die Zeit. Pausenrand oder Dauer ändern verschiebt folgende Elemente. Einpassen berücksichtigt Endpausen.

Ein Pad anklicken wählt es zum Bearbeiten, ohne Wiedergabe auszulösen. Bearbeitung, Wiedergabe, Vormerkung und Vorhören sind getrennt. Sequencer und Arranger nutzen denselben Definitionseditor. Änderungen gelten für alle Vorkommen; Längenänderungen verschieben Folgematerial. Unbenutzte Definitionen und leere Entwürfe bleiben erhalten. Leere Entwürfe lassen sich nicht platzieren oder vorhören; verwendete Definitionen nicht leeren oder löschen. Verwendungen werden angezeigt. Duplizieren behält die Referenz; Variation erstellen kopiert die Definition oder nutzt einen freien Pad-Platz.

Wiedergabequelle wählt Arrangement oder Manuelle Pads. Am Ende bietet im Arranger Spur stoppen oder Spursequenz wiederholen. Neue Geräte stoppen; importierte Einstellungen bleiben erhalten. Leere Spuren sind manuell; das erste Element aktiviert Arrangement. Ausgewählten Bereich wiederholen ist der gemeinsame Transport-Loop.

Vorhören wiederholt ein Pad oder eine Phrase ab der nächsten Pad-/Pausengrenze nur auf dieser Spur. Andere Spuren laufen weiter. Zurück zum Arrangement rekonstruiert an der nächsten Grenze die aktuelle Songposition, auch in Pausen oder nach dem Spur-Ende. Vorhören stoppen stoppt diese Spur ohne automatischen Neustart. Bei gestopptem Transport startet Vorhören nur diese Spur. Positionswechsel und Loops starten das Vorhören beim ersten Token; vorgemerkte Vorhörwechsel gelten am Ziel. Songgrenzen gelten weiterhin.

Arranger-Play beendet Vorhören, startet Arrangement-Spuren und stoppt manuelle Sequencer. Stop beendet Vorhören und Arrangement-Spuren; unabhängig gestartete manuelle Spuren laufen weiter. Live-Arpeggiatoren bleiben unabhängig. Vorhörzustände werden weder gespeichert noch exportiert; musikalische Änderungen werden normal gespeichert.`,
  french: `## Ordre du morceau et phrases réutilisables

Le triangle à côté du nom de piste ouvre ou ferme son éditeur. Cliquer une occurrence l’ouvre ; cliquer un espace vide efface les sélections sans changer l’ouverture. Motifs et phrases et Réglages de lecture ont leurs propres volets, fermés par défaut. Fermer conserve le contexte d’édition ; Nouveau/Charger/Importer réinitialise la disposition.

Muet/Solo agit uniquement sur cette piste, même si plusieurs pistes partagent un instrument. Plusieurs solos sont possibles ; Muet explicite prime. Un bouton Muet ambre en pointillés indique l’exclusion par un autre Solo. Les pistes muettes avancent toujours ; leur réactivation reprend les événements futurs à la position actuelle. Les notes en cours se terminent normalement ; les valeurs CC restent jusqu’à une nouvelle mise à jour. Les lignes de batterie changent ensemble. Solo conserve les entrées et traitements d’arpégiateur nécessaires ; Muet explicite reste prioritaire. Le MIDI externe et les arpégiateurs Live indépendants restent hors de la sélection Solo. Ces contrôles survivent au redémarrage du moteur, se réinitialisent sur Nouveau/Charger/Importer ou rechargement et ne sont jamais sauvegardés ni exportés. Le mixeur reste indépendant.

Seul l’arrangeur multipiste modifie l’ordre du morceau. Sélectionnez une piste et utilisez la palette de pads, groupes, supergroupes et silences. Glissez ou ajoutez dans un espace libre ; les destinations occupées sont refusées. Insérer et décaler la suite agit aux limites des éléments sur cette piste. Suppr/Retour arrière laisse un silence équivalent ; Supprimer et fermer l’espace retire la durée. Redimensionner un silence décale la suite. Ajuster inclut les silences finaux.

Cliquer sur un pad le sélectionne pour l’édition sans le lancer. Édition, Lecture, En attente et Écoute temporaire sont distincts. Le séquenceur et l’action Modifier de l’arrangeur partagent l’éditeur de définitions. Les changements affectent toutes les occurrences ; la durée décale les suivantes. Les définitions inutilisées et brouillons vides restent enregistrés. Un brouillon vide ne peut être placé ni écouté ; une définition référencée ne peut être vidée ni supprimée. Ses utilisations sont affichées. Dupliquer conserve la référence ; Créer une variation copie la définition ou utilise un pad libre.

Source de lecture choisit Arrangement ou Pads manuels. À la fin choisit Arrêter la piste ou Répéter la séquence dans l’arrangeur. Les nouveaux appareils s’arrêtent ; les réglages importés restent intacts. Une piste vide est manuelle ; son premier élément active Arrangement. Boucler la plage sélectionnée commande la boucle commune.

Écouter répète temporairement un pad ou une phrase sur cette piste dès la prochaine limite de pad/silence. Les autres pistes continuent. Retour à l’arrangement reprend à la prochaine limite la position actuelle, y compris un silence ou une piste terminée. Arrêter l’écoute stoppe cette piste sans relancer son arrangement. Transport arrêté, seule cette piste démarre. Les déplacements et boucles reprennent l’écoute au premier élément ; les changements d’écoute en attente s’appliquent à destination. Les limites du morceau restent prioritaires.

Play termine les écoutes, lance les pistes Arrangement et arrête les séquenceurs manuels. Stop termine les écoutes et pistes Arrangement, en préservant les pistes manuelles lancées séparément. Les arpégiateurs Live restent indépendants. L’écoute temporaire n’est ni sauvegardée ni exportée ; les modifications musicales le sont.`,
  spanish: `## Orden del tema y frases reutilizables

El triángulo junto al nombre abre o cierra el editor de pista. Pulsar una aparición lo abre; pulsar un hueco borra las selecciones sin cambiar la apertura. Patrones y frases y Ajustes de reproducción tienen sus propios paneles, cerrados por defecto. Cerrar conserva el contexto de edición; Nuevo/Cargar/Importar restablece el diseño.

Mute/Solo afecta solo a esta pista, aunque varias compartan instrumento. Se permiten varios solos; Mute explícito tiene prioridad. Mute ámbar discontinuo indica exclusión por otro Solo. Las pistas silenciadas siguen avanzando; reactivarlas retoma eventos futuros en la posición actual. Las notas activas terminan normalmente; los valores CC permanecen hasta otra actualización. Las filas de batería cambian juntas. Solo conserva entradas y procesamiento de arpegiador necesarios; Mute explícito sigue teniendo prioridad. El MIDI externo y los arpegiadores Live independientes quedan fuera de Solo. Estos controles sobreviven al reinicio del motor, se restablecen con Nuevo/Cargar/Importar o recarga y nunca se guardan ni exportan. El mezclador sigue independiente.

Solo el arreglador multipista edita el orden del tema. Selecciona una pista y usa su paleta de pads, grupos, supergrupos y silencios. Arrastra o añade en un hueco libre; se rechazan destinos ocupados. Insertar y desplazar los siguientes actúa en límites de elementos de esta pista. Supr/Retroceso deja silencio de igual duración; Eliminar y cerrar hueco retira el tiempo. Cambiar el borde o duración de un silencio desplaza lo siguiente. Ajustar incluye silencios finales.

Pulsar un pad lo selecciona para editar sin lanzarlo. Edición, Reproducción, En espera y Escucha temporal son estados separados. Secuenciadores y Editar del arreglador comparten el editor de definiciones. Los cambios afectan todas las apariciones; cambiar duración desplaza las siguientes. Se conservan definiciones sin usar y borradores vacíos. Un borrador vacío no puede colocarse ni escucharse; una definición referenciada no puede vaciarse ni borrarse. Se muestran sus usos. Duplicar conserva la referencia; Crear una variación copia la definición o usa un pad libre.

Fuente de reproducción elige Arreglo o Pads manuales. Al finalizar elige Detener pista o Repetir secuencia en el arreglador. Los dispositivos nuevos se detienen; se conservan los ajustes importados. Una pista vacía es manual; su primer elemento activa Arreglo. Repetir intervalo seleccionado es el bucle compartido.

Escuchar repite temporalmente un pad o frase de esta pista desde el próximo límite de pad/silencio. Las demás continúan. Volver al arreglo restaura en el próximo límite la posición actual, incluso silencios o pistas terminadas. Detener escucha para esta pista sin reiniciar su arreglo. Con transporte detenido inicia solo esta pista. Saltos y bucles reinician la escucha desde su primer elemento; los cambios de escucha pendientes se aplican en el destino. Los límites del tema siguen vigentes.

Play termina las escuchas, inicia pistas Arreglo y detiene secuenciadores manuales. Stop termina escuchas y pistas Arreglo, conservando pistas manuales iniciadas aparte. Los arpegiadores Live siguen independientes. La escucha temporal no se guarda ni exporta; los cambios musicales sí.`
};
