import type { GuiLanguage } from "../types";

export const arrangementHelp: Record<GuiLanguage, string> = {
  english: `## Song order and reusable phrases

Pads are named 1–8 in the arranger and #1–#8 in sequencers. Defaults are green pads, red groups, violet supergroups and dark rests. Numbers identify pad slots, not duration. Right-click a musical occurrence or palette entry to Set colour or Reset colour. A custom colour is saved for that definition in this lane and shared by its palette and occurrences; sequencer colours stay unchanged.

The triangle beside a track title opens or closes its editor. Click anywhere in an occurrence to select it and open the lane; Cmd/Ctrl-click toggles selection. Empty timeline space clears highlights and sets Position without changing expansion. Playback settings has its own disclosure. Closing preserves editing context; New/Load/Import resets it. Sequencers retain their separate Patterns and phrases panel.

Mute/Solo affects this lane only, even when lanes share an instrument. Multiple solos are allowed; explicit mute wins. Dashed amber Mute means suppressed by another Solo. Muted lanes keep advancing; unmute resumes future events at the current position. Existing notes release normally and CC values stay at their last applied value until another update. Drummer rows act together. Solo preserves needed arpeggiator inputs and processing; explicit mute still wins. External MIDI and independent Live arpeggiators are outside solo selection. Lane controls survive engine restart but reset on New/Load/Import or reload and are never saved or exported. Mixer controls remain independent.

Only the multitrack arranger edits song order. The palette hides pattern pads containing only rest steps and keeps their original numbers. Drag pads, groups, supergroups or rests from the wrapping palette beside Position (master beats). At a boundary, dropping inserts and shifts later material on this lane. Inside a rest, musical material must fit. Beyond the end, pauses fill the gap. Occupied musical destinations are rejected. Drag a contiguous selection to move it, leaving silence at its source. The preview shows the resolved position and duration. There is no Add, Paste, Duplicate or number-key placement in the arranger.

Right-click for editing actions; Shift+F10 opens the same menu from the keyboard and Escape dismisses it. Double-click a pad to open its sequencer editor. Group at least two contiguous pads/rests; a Supergroup may also contain groups. Ungroup expands one level and retains the definition. Rearrange, then regroup as a new definition or explicitly update an existing one. Updating affects every reference and duration changes shift following material. Create variation makes an independent copy, using a free slot for pads. Unused definitions remain available; palette deletion is disabled while referenced. Empty drafts cannot be placed or auditioned. Delete/Backspace leaves equivalent silence; Shift+Delete or Remove and close gap closes time. Resize rests by their right edge or the Duration menu. Fit includes trailing rests.

Playback source selects Arrangement or Manual pads. At end selects Stop track or Repeat track sequence in the arranger. New devices stop; imported repeat settings remain. Empty lanes are manual; adding their first item selects Arrangement. Loop selected range is a separate shared loop.

Hold a speaker for 250 ms to preview a pad or phrase from its first token at the next available audio block, without waiting for a musical boundary. Short clicks do nothing. Preview repeats while held; releasing restores the lane’s previous arrangement, manual playback or sequencer audition at the current shared-clock position. Previously stopped lanes stay stopped. Other tracks continue. Space/Enter supports the same hold/release gesture. Cancellation, focus loss, collapse and navigation end the preview. Seeks and loops restart held previews at their first token; song boundaries remain authoritative.

Sequencer Audition keeps its existing boundary-based behavior: it repeats until Stop audition or Return to arrangement, with return at the next boundary. Arranger Play clears auditions/previews, starts Arrangement lanes and stops Manual pads sequencers. Stop clears auditions/previews and stops Arrangement lanes while preserving other independently started manual tracks. Live arpeggiators remain independent. Preview and audition state is never saved or exported; musical edits and custom colours save normally.`,
  german: `## Songfolge und wiederverwendbare Phrasen

Pads heißen im Arranger 1–8 und in Sequencern #1–#8. Standardfarben sind Grün für Pads, Rot für Gruppen, Violett für Supergruppen und Dunkel für Pausen. Nummern bezeichnen Pad-Plätze, keine Dauer. Rechtsklick auf ein musikalisches Vorkommen oder einen Paletteneintrag bietet Farbe festlegen und Farbe zurücksetzen. Eine eigene Farbe wird für die Definition dieser Spur gespeichert und gilt für Palette und alle Vorkommen; Sequencer-Farben bleiben unverändert.

Das Dreieck neben dem Spurnamen öffnet oder schließt den Editor. Ein Klick irgendwo im Element wählt es und öffnet die Spur; Cmd/Strg-Klick schaltet die Auswahl um. Freie Timeline-Fläche hebt Markierungen auf und setzt Position, ohne die Spur zu öffnen oder zu schließen. Wiedergabeeinstellungen haben einen eigenen Bereich. Schließen erhält den Bearbeitungszustand; Neu/Laden/Import setzt ihn zurück. Sequencer behalten ihren separaten Bereich Patterns und Phrasen.

Mute/Solo wirkt nur auf diese Spur, auch bei gemeinsamem Instrument. Mehrere Solos sind möglich; explizites Mute hat Vorrang. Ein gestricheltes bernsteinfarbenes Mute zeigt Unterdrückung durch ein anderes Solo. Stumme Spuren laufen zeitlich weiter und steigen bei Freigabe an der aktuellen Position wieder ein. Klingende Noten klingen normal aus; CC-Werte bleiben bis zur nächsten Aktualisierung bestehen. Drum-Zeilen werden gemeinsam geschaltet. Solo erhält benötigte Arpeggiator-Eingänge und Verarbeitung; explizites Mute gilt weiter. Externes MIDI und unabhängige Live-Arpeggiatoren bleiben außerhalb der Solo-Auswahl. Spurkontrollen überstehen einen Engine-Neustart, werden bei Neu/Laden/Import oder Browser-Neuladen zurückgesetzt und nie gespeichert oder exportiert. Mixer-Kontrollen bleiben unabhängig.

Nur der Multitrack Arranger bearbeitet die Songfolge. Die Palette blendet Pattern-Pads mit ausschließlich Pausenschritten aus und behält ihre ursprünglichen Nummern. Pads, Gruppen, Supergruppen und Pausen aus der umbrechenden Palette neben Position (Master-Beats) ziehen. An Elementgrenzen fügt Ablegen ein und verschiebt Folgematerial dieser Spur. In eine Pause muss musikalisches Material hineinpassen. Hinter dem Ende füllen Pausen den Abstand. Belegte musikalische Ziele werden abgelehnt. Zusammenhängende Auswahl verschieben lässt Stille am Ursprung. Die Vorschau zeigt Zielposition und Dauer. Hinzufügen, Einfügen aus der Zwischenablage, Duplizieren und Platzieren per Zifferntaste entfallen im Arranger.

Rechtsklick öffnet Bearbeitungsaktionen; per Tastatur öffnet Umschalt+F10 dasselbe Menü, Escape schließt es. Doppelklick auf ein Pad öffnet seinen Sequencer-Editor. Mindestens zwei benachbarte Pads/Pausen bilden eine Gruppe; Supergruppen dürfen auch Gruppen enthalten. Gruppierung aufheben erweitert eine Ebene und behält die Definition. Neu anordnen und danach als neue Definition gruppieren oder eine bestehende ausdrücklich aktualisieren. Aktualisieren betrifft alle Referenzen; Längenänderungen verschieben Folgematerial. Variation erstellen erzeugt eine unabhängige Kopie, bei Pads in einem freien Platz. Unbenutzte Definitionen bleiben erhalten; Löschen aus der Palette ist bei Referenzen gesperrt. Leere Entwürfe lassen sich nicht platzieren oder vorhören. Delete/Backspace lässt gleich lange Stille; Umschalt+Delete oder Entfernen und Lücke schließen verkürzt die Zeit. Pausen am rechten Rand oder im Dauer-Menü ändern. Einpassen berücksichtigt Endpausen.

Wiedergabequelle wählt Arrangement oder Manuelle Pads. Am Ende bietet im Arranger Spur stoppen oder Spursequenz wiederholen. Neue Geräte stoppen; importierte Einstellungen bleiben erhalten. Leere Spuren sind manuell; das erste Element aktiviert Arrangement. Ausgewählten Bereich wiederholen ist der gemeinsame Transport-Loop.

Lautsprechersymbol 250 ms halten: Pad oder Phrase startet beim ersten Element im nächsten verfügbaren Audioblock, ohne auf eine musikalische Grenze zu warten. Kurze Klicks bewirken nichts. Während des Haltens wird wiederholt; Loslassen stellt das vorherige Arrangement, manuelle Spiel oder Sequencer-Vorhören an der aktuellen gemeinsamen Zeitposition wieder her. Zuvor gestoppte Spuren bleiben gestoppt. Andere Spuren laufen weiter. Leertaste/Enter unterstützt dasselbe Halten und Loslassen. Abbruch, Fokusverlust, Einklappen und Navigation beenden die Vorschau. Positionswechsel und Loops starten gehaltene Vorschauen beim ersten Element; Songgrenzen bleiben maßgeblich.

Sequencer-Vorhören bleibt grenzbasiert: Es wiederholt bis Vorhören stoppen oder Zurück zum Arrangement; die Rückkehr erfolgt an der nächsten Grenze. Arranger-Play beendet Vorhören/Vorschauen, startet Arrangement-Spuren und stoppt manuelle Sequencer. Stop beendet Vorhören/Vorschauen und Arrangement-Spuren; andere unabhängig gestartete manuelle Spuren laufen weiter. Live-Arpeggiatoren bleiben unabhängig. Vorhörzustände werden nie gespeichert oder exportiert; musikalische Änderungen und eigene Farben werden normal gespeichert.`,
  french: `## Ordre du morceau et phrases réutilisables

Les pads sont nommés 1–8 dans l’arrangeur et #1–#8 dans les séquenceurs. Couleurs par défaut : pads verts, groupes rouges, supergroupes violets et silences sombres. Les numéros désignent des emplacements, pas des durées. Un clic droit sur une occurrence musicale ou une entrée de palette propose Définir la couleur et Réinitialiser la couleur. La couleur est sauvegardée pour cette définition de piste et partagée par sa palette et toutes ses occurrences ; les couleurs du séquenceur restent inchangées.

Le triangle près du nom ouvre ou ferme l’éditeur. Cliquez n’importe où dans une occurrence pour la sélectionner et ouvrir la piste ; Cmd/Ctrl-clic bascule la sélection. Cliquer un espace vide efface les sélections et règle Position sans changer l’ouverture. Réglages de lecture possède son propre volet. Fermer conserve le contexte ; Nouveau/Charger/Importer le réinitialise. Les séquenceurs conservent leur volet Motifs et phrases séparé.

Muet/Solo agit uniquement sur cette piste, même si plusieurs pistes partagent un instrument. Plusieurs solos sont possibles ; Muet explicite prime. Un bouton Muet ambre en pointillés indique l’exclusion par un autre Solo. Les pistes muettes avancent toujours ; leur réactivation reprend les événements futurs à la position actuelle. Les notes en cours se terminent normalement ; les valeurs CC restent jusqu’à une nouvelle mise à jour. Les lignes de batterie changent ensemble. Solo conserve les entrées et traitements d’arpégiateur nécessaires ; Muet explicite reste prioritaire. Le MIDI externe et les arpégiateurs Live indépendants restent hors de la sélection Solo. Ces contrôles survivent au redémarrage du moteur, se réinitialisent sur Nouveau/Charger/Importer ou rechargement et ne sont jamais sauvegardés ni exportés. Le mixeur reste indépendant.

Seul l’arrangeur multipiste modifie l’ordre du morceau. La palette masque les pads ne contenant que des pas de silence et conserve leurs numéros d’origine. Glissez pads, groupes, supergroupes ou silences depuis la palette à côté de Position (temps maîtres), avec retour à la ligne. À une limite, le dépôt insère et décale la suite de cette piste. Dans un silence, le contenu musical doit tenir. Après la fin, des silences comblent l’écart. Les destinations musicales occupées sont refusées. Déplacer une sélection contiguë laisse du silence à sa source. L’aperçu montre la position et la durée retenues. L’arrangeur ne propose plus Ajouter, Coller, Dupliquer ni le placement par touches numériques.

Clic droit pour les actions ; Maj+F10 ouvre le même menu au clavier et Échap le ferme. Double-cliquez un pad pour ouvrir son séquenceur. Un groupe requiert au moins deux pads/silences contigus ; un supergroupe accepte aussi des groupes. Dégrouper développe un niveau et conserve la définition. Réorganisez puis regroupez en nouvelle définition ou mettez explicitement à jour une définition existante. Une mise à jour affecte toutes les références ; changer la durée décale la suite. Créer une variation produit une copie indépendante, dans un emplacement libre pour un pad. Les définitions inutilisées restent disponibles ; leur suppression dans la palette est bloquée si elles sont référencées. Un brouillon vide ne peut être placé ni écouté. Suppr/Retour arrière laisse un silence équivalent ; Maj+Suppr ou Supprimer et fermer l’espace retire la durée. Redimensionnez un silence par son bord droit ou le menu Durée. Ajuster inclut les silences finaux.

Source de lecture choisit Arrangement ou Pads manuels. À la fin choisit Arrêter la piste ou Répéter la séquence dans l’arrangeur. Les nouveaux appareils s’arrêtent ; les réglages importés restent intacts. Une piste vide est manuelle ; son premier élément active Arrangement. Boucler la plage sélectionnée commande la boucle commune.

Maintenez un haut-parleur 250 ms pour écouter le pad ou la phrase depuis son début au prochain bloc audio disponible, sans attendre une limite musicale. Un clic bref ne fait rien. L’écoute se répète pendant le maintien ; relâcher restaure l’arrangement, le jeu manuel ou l’écoute du séquenceur précédent à la position actuelle de l’horloge commune. Une piste auparavant arrêtée reste arrêtée. Les autres continuent. Espace/Entrée permet le même maintien au clavier. Annulation, perte de focus, fermeture et navigation terminent l’aperçu. Déplacements et boucles reprennent les aperçus maintenus au premier élément ; les limites du morceau restent prioritaires.

L’écoute du séquenceur conserve son fonctionnement aux limites : elle répète jusqu’à Arrêter l’écoute ou Retour à l’arrangement, avec retour à la prochaine limite. Play efface écoutes et aperçus, lance les pistes Arrangement et arrête les séquenceurs manuels. Stop efface écoutes et aperçus et arrête les pistes Arrangement, tout en préservant les autres pistes manuelles lancées séparément. Les arpégiateurs Live restent indépendants. Les états d’écoute ne sont jamais sauvegardés ni exportés ; les modifications musicales et couleurs personnalisées le sont.`,
  spanish: `## Orden del tema y frases reutilizables

Los pads se llaman 1–8 en el arreglador y #1–#8 en los secuenciadores. Colores predeterminados: pads verdes, grupos rojos, supergrupos violetas y silencios oscuros. Los números identifican espacios, no duraciones. El clic derecho en una aparición musical o entrada de paleta ofrece Establecer color y Restablecer color. El color se guarda para esa definición de pista y lo comparten su paleta y todas sus apariciones; los colores del secuenciador no cambian.

El triángulo junto al nombre abre o cierra el editor. Pulsa cualquier zona de una aparición para seleccionarla y abrir la pista; Cmd/Ctrl-clic alterna la selección. Un espacio vacío borra las selecciones y establece Posición sin cambiar la apertura. Ajustes de reproducción tiene su propio panel. Cerrar conserva el contexto; Nuevo/Cargar/Importar lo restablece. Los secuenciadores mantienen su panel separado Patrones y frases.

Mute/Solo afecta solo a esta pista, aunque varias compartan instrumento. Se permiten varios solos; Mute explícito tiene prioridad. Mute ámbar discontinuo indica exclusión por otro Solo. Las pistas silenciadas siguen avanzando; reactivarlas retoma eventos futuros en la posición actual. Las notas activas terminan normalmente; los valores CC permanecen hasta otra actualización. Las filas de batería cambian juntas. Solo conserva entradas y procesamiento de arpegiador necesarios; Mute explícito sigue teniendo prioridad. El MIDI externo y los arpegiadores Live independientes quedan fuera de Solo. Estos controles sobreviven al reinicio del motor, se restablecen con Nuevo/Cargar/Importar o recarga y nunca se guardan ni exportan. El mezclador sigue independiente.

Solo el arreglador multipista edita el orden del tema. La paleta oculta los pads que solo contienen pasos de silencio y conserva sus números originales. Arrastra pads, grupos, supergrupos o silencios desde la paleta con ajuste de línea junto a Posición (pulsos maestros). En un límite, soltar inserta y desplaza lo siguiente en esa pista. Dentro de un silencio, el material musical debe caber. Tras el final, se añaden silencios para cubrir el hueco. Se rechazan destinos musicales ocupados. Mover una selección contigua deja silencio en su origen. La vista previa muestra la posición y duración resueltas. El arreglador ya no ofrece Añadir, Pegar, Duplicar ni colocación por teclas numéricas.

Clic derecho para las acciones; Mayús+F10 abre el mismo menú con el teclado y Escape lo cierra. Doble clic en un pad abre su secuenciador. Un grupo requiere al menos dos pads/silencios contiguos; un supergrupo también admite grupos. Desagrupar expande un nivel y conserva la definición. Reorganiza y vuelve a agrupar como definición nueva o actualiza explícitamente una existente. Actualizar afecta todas las referencias; cambiar la duración desplaza lo siguiente. Crear variación genera una copia independiente, en un espacio libre si es un pad. Las definiciones sin usar se conservan; la eliminación desde la paleta se bloquea mientras haya referencias. Los borradores vacíos no pueden colocarse ni escucharse. Supr/Retroceso deja silencio equivalente; Mayús+Supr o Eliminar y cerrar hueco retira el tiempo. Ajusta silencios desde el borde derecho o el menú Duración. Ajustar incluye los silencios finales.

Fuente de reproducción elige Arreglo o Pads manuales. Al finalizar elige Detener pista o Repetir secuencia en el arreglador. Los dispositivos nuevos se detienen; se conservan los ajustes importados. Una pista vacía es manual; su primer elemento activa Arreglo. Repetir intervalo seleccionado es el bucle compartido.

Mantén un altavoz 250 ms para escuchar el pad o frase desde su inicio en el siguiente bloque de audio disponible, sin esperar un límite musical. Un clic breve no hace nada. Se repite mientras mantienes pulsado; soltar restaura el arreglo, reproducción manual o escucha previa del secuenciador en la posición actual del reloj compartido. Las pistas antes detenidas siguen detenidas. Las demás continúan. Espacio/Intro ofrece el mismo gesto con el teclado. Cancelación, pérdida de foco, cierre y navegación terminan la escucha. Saltos y bucles reinician las escuchas mantenidas desde el primer elemento; los límites del tema siguen vigentes.

La escucha del secuenciador mantiene su funcionamiento por límites: repite hasta Detener escucha o Volver al arreglo, con retorno en el siguiente límite. Play borra escuchas y vistas previas, inicia pistas Arreglo y detiene secuenciadores manuales. Stop borra escuchas y vistas previas y detiene pistas Arreglo, conservando las otras pistas manuales iniciadas aparte. Los arpegiadores Live siguen independientes. Los estados de escucha nunca se guardan ni exportan; los cambios musicales y colores personalizados sí.`
};
