import type { GuiLanguage } from "../types";
const rows = {
  role: ["Role", "Rolle", "Rôle", "Función"],
  routeLimit: ["A performance supports up to 1,024 channel connections.", "Eine Performance unterstützt bis zu 1.024 Kanalverbindungen.", "Une performance accepte jusqu’à 1 024 connexions de canaux.", "Una interpretación admite hasta 1.024 conexiones de canales."],
  instanceLimit: ["A performance supports up to 64 patch instances, including processors.", "Eine Performance unterstützt bis zu 64 Patch-Instanzen einschließlich Prozessoren.", "Une performance accepte jusqu’à 64 instances de patch, processeurs compris.", "Una interpretación admite hasta 64 instancias de patch, incluidos los procesadores."],
  groupName: ["Group name", "Gruppenname", "Nom du groupe", "Nombre del grupo"],
  layout: ["Layout", "Anordnung", "Disposition", "Disposición"],
  portPurpose: ["Port purpose", "Port-Funktion", "Fonction du port", "Función del puerto"],
  mainInput: ["Main input", "Haupteingang", "Entrée principale", "Entrada principal"],
  brokenRoute: ["Repair route", "Verbindung reparieren", "Réparer la route", "Reparar ruta"],
  feedback: ["Feedback cycle: remove a connection", "Rückkopplung: Verbindung entfernen", "Boucle : supprimer une connexion", "Bucle: eliminar una conexión"],
  noOutput: ["Connect an audio output", "Audioausgang verbinden", "Connecter une sortie audio", "Conectar una salida de audio"],
  noInput: ["Select an audio source", "Audioquelle wählen", "Choisir une source audio", "Seleccionar fuente de audio"],
  parallelOutput: ["Review parallel output paths", "Parallele Ausgänge prüfen", "Vérifier les sorties parallèles", "Revisar salidas paralelas"],
  incompleteStereo: ["Complete stereo mapping", "Stereo-Zuordnung vervollständigen", "Compléter la connexion stéréo", "Completar conexión estéreo"],
  unusedInput: ["Unused input ports", "Unbenutzte Eingänge", "Entrées inutilisées", "Entradas sin usar"],
  unusedOutput: ["Unused output ports", "Unbenutzte Ausgänge", "Sorties inutilisées", "Salidas sin usar"],
  mixer: ["Mixer", "Mischpult", "Mixeur", "Mezclador"],
  master: ["Master", "Master", "Master", "Máster"],
  direct: ["Direct Audio Output", "Direkter Audioausgang", "Sortie audio directe", "Salida de audio directa"],
  audioOutput: ["Audio Output", "Audioausgang", "Sortie audio", "Salida de audio"],
  gain: ["Gain", "Pegel", "Gain", "Ganancia"],
  balance: ["Pan / Balance", "Panorama / Balance", "Panoramique / Balance", "Panorama / Balance"],
  mute: ["Mute", "Stumm", "Muet", "Silenciar"],
  solo: ["Solo", "Solo", "Solo", "Solo"],
  sends: ["Sends", "Sends", "Envois", "Envíos"],
  pre: ["Pre-fader", "Vor Fader", "Pré-fader", "Pre-fader"],
  post: ["Post-fader", "Nach Fader", "Post-fader", "Post-fader"],
  routing: ["Audio routing", "Audio-Routing", "Routage audio", "Rutas de audio"],
  source: ["Source", "Quelle", "Source", "Origen"],
  destination: ["Destination", "Ziel", "Destination", "Destino"],
  mapping: ["Exact channel mapping", "Genaue Kanalzuordnung", "Correspondance exacte des canaux", "Asignación exacta de canales"],
  route: ["Route", "Verbindung", "Route", "Ruta"],
  send: ["Send", "Send", "Envoi", "Envío"],
  main: ["Main output", "Hauptausgang", "Sortie principale", "Salida principal"],
  add: ["Add", "Hinzufügen", "Ajouter", "Añadir"],
  remove: ["Remove", "Entfernen", "Supprimer", "Eliminar"],
  edit: ["Edit patch", "Patch bearbeiten", "Modifier le patch", "Editar patch"],
  stop: ["Stop to edit routing", "Stoppen, um Routing zu bearbeiten", "Arrêter pour modifier le routage", "Detener para editar rutas"],
  routeMaster: ["Route through Master", "Über Master leiten", "Router via le Master", "Enviar al Máster"],
  createMaster: ["Create neutral Master", "Neutralen Master erstellen", "Créer un Master neutre", "Crear Máster neutro"],
  additional: ["Additional output groups", "Weitere Ausgangsgruppen", "Groupes de sortie supplémentaires", "Grupos de salida adicionales"],
  inserts: ["Inserts", "Insert-Effekte", "Inserts", "Inserciones"],
  custom: ["Custom routing", "Benutzerdefiniertes Routing", "Routage personnalisé", "Rutas personalizadas"],
  matrix: ["Destination matrix", "Zielmatrix", "Matrice des destinations", "Matriz de destinos"],
  diagram: ["Routing diagram", "Routing-Diagramm", "Schéma de routage", "Diagrama de rutas"],
  diagnostics: ["Routing diagnostics", "Routing-Diagnose", "Diagnostic du routage", "Diagnóstico de rutas"],
  validate: ["Check routing", "Routing prüfen", "Vérifier le routage", "Comprobar rutas"],
  structural: ["Connectivity is structural; meters show measured audio.", "Verbindungen zeigen die Struktur; Pegelmesser zeigen gemessenes Audio.", "Les connexions décrivent la structure ; les vumètres mesurent l’audio.", "Las conexiones muestran la estructura; los medidores muestran el audio real."],
  migration: ["Level now changes audio amplitude instead of MIDI velocity. Velocity-sensitive patches may sound different. Your previous levels were converted to dB.", "Level ändert jetzt die Audioamplitude statt der MIDI-Velocity. Anschlagabhängige Patches können anders klingen. Die bisherigen Werte wurden in dB umgerechnet.", "Level règle maintenant l’amplitude audio au lieu de la vélocité MIDI. Les patches sensibles à la vélocité peuvent sonner différemment. Les anciens niveaux ont été convertis en dB.", "Level ahora modifica la amplitud de audio en lugar de la velocidad MIDI. Los patches sensibles a la velocidad pueden sonar diferente. Los niveles anteriores se convirtieron a dB."],
  dismiss: ["Dismiss", "Schließen", "Fermer", "Cerrar"],
  stereoInput: ["Stereo Input", "Stereo-Eingang", "Entrée stéréo", "Entrada estéreo"],
  stereoOutput: ["Stereo Output", "Stereo-Ausgang", "Sortie stéréo", "Salida estéreo"],
  expand: ["Show underlying nodes", "Zugrunde liegende Knoten zeigen", "Afficher les nœuds sous-jacents", "Mostrar nodos subyacentes"],
  collapse: ["Collapse", "Einklappen", "Réduire", "Contraer"],
  activation: ["Activation", "Aktivierung", "Activation", "Activación"],
  midi: ["MIDI notes", "MIDI-Noten", "Notes MIDI", "Notas MIDI"],
  continuous: ["Continuous", "Dauerhaft", "Continue", "Continua"],
  instrument: ["Playable instrument", "Spielbares Instrument", "Instrument jouable", "Instrumento tocable"],
  effect: ["Audio effect", "Audioeffekt", "Effet audio", "Efecto de audio"],
  output: ["Output / Master processor", "Ausgang / Master-Prozessor", "Processeur de sortie / Master", "Procesador de salida / Máster"],
  empty: ["Empty patch", "Leerer Patch", "Patch vide", "Patch vacío"],
  audition: ["Audition", "Vorhören", "Écouter", "Escuchar"],
  isolated: ["Isolated", "Isoliert", "Isolé", "Aislado"],
  inPerformance: ["In current performance", "In aktueller Performance", "Dans la performance actuelle", "En la interpretación actual"],
  stopAudition: ["Stop and audition", "Stoppen und vorhören", "Arrêter et écouter", "Detener y escuchar"],
  closeAudition: ["Close audition · transport stays stopped", "Vorhören schließen · Transport bleibt gestoppt", "Fermer l’écoute · transport arrêté", "Cerrar escucha · transporte detenido"],
  prepare: ["Prepare audition", "Vorhören vorbereiten", "Préparer l’écoute", "Preparar escucha"],
  testSource: ["Test source", "Testquelle", "Source de test", "Fuente de prueba"],
  missing: ["Missing reference", "Fehlender Verweis", "Référence manquante", "Referencia ausente"],
  silent: ["Muted or silent path", "Stummer oder lautloser Signalweg", "Chemin muet ou silencieux", "Ruta silenciada o en silencio"],
  reset: ["Double-click to reset. Arrow keys adjust; Home/End select limits.", "Doppelklick setzt zurück. Pfeiltasten ändern; Pos1/Ende wählen Grenzen.", "Double-cliquez pour réinitialiser. Flèches : régler ; Début/Fin : limites.", "Doble clic para restablecer. Flechas: ajustar; Inicio/Fin: límites."],
} as const;
export function audioCopy(language: GuiLanguage) {
  const index = ({ english: 0, german: 1, french: 2, spanish: 3 } as const)[language];
  return (key: keyof typeof rows): string => rows[key][index];
}
