export const drummerRatchetHelp = {
  english: `### Ratchets and velocity ramps

Right-click a drum cell or press Shift+F10 for Step properties. Ratchets (1–8) divide one local step into evenly spaced hits; ×N marks the roll. Enable Velocity ramp to interpolate from the cell velocity to Final velocity (0–127). Zero is silent. At count 1 the ramp is ignored but retained. For four hits, 100 → 40 produces 100, 80, 60, 40.

Timing shifts the whole roll; the next active cell in the same row cuts off remaining hits. Early first rolls start at the boundary on fresh starts or different-pad launches, and anticipate confirmed same-pad repeats. Late tails may cross same-pad boundaries. Stops, seeks, other pads, arrangement rests and finite ends cancel unfinished rolls. Edits affect the next occurrence of a roll already in progress. Editing an inactive cell leaves it inactive; toggling retains its settings, copying and saving preserve them, and Clear Steps resets them. Native bundles and both CSD exports preserve rolls. The panel edits the displayed pad; changing pads, collapsing or removing the target closes it. Escape closes it too.`,
  german: `### Mehrfachanschläge und Anschlagstärke-Verlauf

Rechtsklick oder Umschalt+F10 öffnet Schritteigenschaften. Mehrfachanschläge (1–8) verteilen Anschläge gleichmäßig über einen lokalen Schritt; ×N markiert den Wirbel. Anschlagstärke-Verlauf interpoliert von der Zellen-Anschlagstärke zur Letzten Anschlagstärke (0–127); 0 ist stumm. Bei einem Anschlag bleibt der Verlauf gespeichert, wird aber ignoriert. Vier Anschläge von 100 auf 40 ergeben 100, 80, 60, 40.

Timing verschiebt den ganzen Wirbel; die nächste aktive Zelle derselben Zeile beendet ihn. Frühe erste Wirbel beginnen bei Neustart oder einem anderen Pad an der Grenze, bei bestätigter Wiederholung desselben Pads davor. Späte Wirbel können diese Wiederholungsgrenze überschreiten. Stop, Sprung, anderes Pad, Arrangement-Pause oder Ende brechen offene Wirbel ab. Änderungen gelten für das nächste Auftreten eines bereits laufenden Wirbels. Inaktive Zellen bleiben inaktiv; Umschalten erhält Werte, Kopieren und Speichern übernehmen sie, Schritte löschen setzt sie zurück. Native Bundles und beide CSD-Exporte erhalten Wirbel. Das Bedienfeld bearbeitet das angezeigte Pad und schließt bei Padwechsel, Einklappen, Entfernen oder Escape.`,
  french: `### Répétitions rapides et rampe de vélocité

Clic droit ou Maj+F10 ouvre Propriétés du pas. Répétitions rapides (1–8) répartit les frappes régulièrement sur un pas local ; ×N indique le roulement. Rampe de vélocité interpole entre la vélocité de la cellule et la Vélocité finale (0–127) ; 0 est silencieux. Avec une frappe, la rampe reste mémorisée mais ignorée. Quatre frappes de 100 à 40 donnent 100, 80, 60, 40.

Le placement décale tout le roulement ; la cellule active suivante de la même ligne l'interrompt. Un premier roulement en avance commence à la limite au démarrage ou sur un autre pad, et avant la limite lors d'une répétition confirmée du même pad. Une fin tardive peut franchir cette limite. Arrêt, déplacement, autre pad, pause d'arrangement ou fin annulent les frappes restantes. Les modifications d'un roulement commencé s'appliquent à son prochain passage. Les cellules inactives restent inactives ; basculer conserve les valeurs, copier et sauvegarder les préservent, Effacer pas les réinitialise. Les exports natifs et CSD conservent les roulements. Le panneau modifie le pad affiché et se ferme au changement de pad, au repli, à la suppression ou avec Échap.`,
  spanish: `### Repeticiones rápidas y rampa de velocidad

Clic derecho o Mayús+F10 abre Propiedades del paso. Repeticiones rápidas (1–8) distribuye golpes equidistantes dentro de un paso local; ×N marca el redoble. Rampa de velocidad interpola entre la velocidad de la celda y la Velocidad final (0–127); 0 es silencioso. Con un golpe, la rampa se conserva pero se ignora. Cuatro golpes de 100 a 40 producen 100, 80, 60, 40.

El tiempo desplaza todo el redoble; la siguiente celda activa de la misma fila lo interrumpe. Un primer redoble adelantado empieza en el límite al iniciar o cambiar de pad, y antes del límite al repetir el mismo pad. Una cola tardía puede cruzar ese límite. Parada, salto, otro pad, pausa del arreglo o final cancelan los golpes pendientes. Los cambios en un redoble iniciado se aplican en su próxima aparición. Las celdas inactivas siguen inactivas; alternar conserva valores, copiar y guardar los preservan, Limpiar pasos los restablece. Los exports nativos y CSD conservan redobles. El panel edita el pad mostrado y se cierra al cambiar de pad, contraer, eliminar o pulsar Escape.`
};
