export const melodicStrumHelp = {
  english: `### Step properties and strummed chords

Right-click a melodic note or chord, press Shift+F10, or click its ⋮ button to open Step properties above the grid. Timing remains available on rests. Choose Strum: Off, Low → High or High → Low. Select a chord to enable strumming; removing it retains the settings. Spread is an integer 0–100% of one local grid step, measured from first to last note. The millisecond readout follows tempo, meter, subdivision and speed. At 0% notes play together; at 100% the last note starts at the next step, even if it is empty. Off retains Spread.

Notes are evenly spaced in pitch order. Timing shifts the whole strum. Each note keeps its duration, including HOLD, and may overlap later steps. Repeated pitches retrigger safely; at the same instant, the later logical step wins only for that pitch. At 120 BPM, 4/4, Subdivision 4 and speed 1×, a three-note chord at 40% starts at 0, 25 and 50 ms; at 100% it starts at 0, 62.5 and 125 ms. Melodic steps have no ratchet controls.

Click Timing or ↑/↓ percentage badges to reopen the panel. Copies, hidden steps, saves, native bundles and both CSD exports preserve strumming; Clear Steps resets it. Edits to direction, spread or timing affect the next occurrence of a started strum; HOLD changes still update releases. Same-pad repeats can carry late notes across their boundary. Stop, seek, a different pad, arrangement rests and finite endings cancel unfinished strums. The panel edits the displayed pad and closes on pad changes, collapse, removal, New/Load/Import or Escape.`,
  german: `### Schritteigenschaften und versetzte Akkordanschläge

Rechtsklick auf eine Melodienote oder einen Akkord, Umschalt+F10 oder die Schaltfläche ⋮ öffnet die Schritteigenschaften über dem Raster. Timing bleibt auch für Pausen verfügbar. Akkordanschlag bietet Aus, Tief → Hoch und Hoch → Tief. Ein ausgewählter Akkord aktiviert die Regler; beim Entfernen bleiben die Werte gespeichert. Spreizung ist eine ganze Zahl von 0–100% eines lokalen Rasterschritts, gemessen von der ersten bis zur letzten Note. Die Millisekundenanzeige folgt Tempo, Takt, Unterteilung und Geschwindigkeit. Bei 0% erklingen die Noten gleichzeitig; bei 100% beginnt die letzte am nächsten Schritt, auch wenn dieser leer ist. Aus behält die Spreizung.

Die Noten folgen in gleichmäßigen Abständen ihrer Tonhöhe. Timing verschiebt den gesamten Anschlag. Jede Note behält ihre Dauer einschließlich HOLD und darf spätere Schritte überlappen. Gleiche Tonhöhen werden erneut angeschlagen; bei gleichem Zeitpunkt gewinnt nur für diese Tonhöhe der spätere logische Schritt. Bei 120 BPM, 4/4, Unterteilung 4 und Geschwindigkeit 1× erklingt ein Dreiklang mit 40% bei 0, 25 und 50 ms, mit 100% bei 0, 62,5 und 125 ms. Melodieschritte haben keine Mehrfachanschlag-Regler.

Timing- und ↑/↓-Prozentmarkierungen öffnen das Bedienfeld. Kopieren, verborgene Schritte, Speichern, native Bundles und beide CSD-Exporte erhalten die Werte; Schritte löschen setzt sie zurück. Änderungen an Richtung, Spreizung oder Timing gelten beim nächsten Auftreten eines begonnenen Anschlags; HOLD ändert weiterhin die Freigabe. Wiederholungen desselben Pads erlauben späte Noten über die Grenze. Stop, Sprung, anderes Pad, Arrangement-Pause und Ende brechen offene Anschläge ab. Das Bedienfeld bearbeitet das angezeigte Pad und schließt bei Padwechsel, Einklappen, Entfernen, Neu/Laden/Import oder Escape.`,
  french: `### Propriétés du pas et accords égrenés

Clic droit sur une note mélodique ou un accord, Maj+F10 ou le bouton ⋮ ouvre Propriétés du pas au-dessus de la grille. Le placement reste disponible sur les silences. Accord égrené propose Désactivé, Grave → Aigu et Aigu → Grave. Sélectionnez un accord pour activer les réglages ; le retirer conserve les valeurs. Étalement est un entier de 0–100% d’un pas local, mesuré de la première à la dernière note. Les millisecondes suivent tempo, mesure, subdivision et vitesse. À 0%, les notes jouent ensemble ; à 100%, la dernière commence au pas suivant, même vide. Désactivé conserve l’étalement.

Les notes sont régulièrement espacées selon leur hauteur. Le placement décale tout l’accord égrené. Chaque note conserve sa durée, y compris HOLD, et peut chevaucher les pas suivants. Une même hauteur est redéclenchée ; au même instant, le pas logique suivant gagne uniquement pour cette hauteur. À 120 BPM, 4/4, subdivision 4 et vitesse 1×, trois notes à 40% commencent à 0, 25 et 50 ms ; à 100%, à 0, 62,5 et 125 ms. Les pas mélodiques n’ont pas de réglage de répétitions rapides.

Les badges de placement et de pourcentage ↑/↓ rouvrent le panneau. Copies, pas masqués, sauvegardes, bundles natifs et exports CSD conservent les valeurs ; Effacer pas les réinitialise. Les modifications de direction, étalement ou placement s’appliquent au prochain passage d’un accord déjà commencé ; HOLD ajuste toujours les fins. Les répétitions du même pad permettent des notes tardives au-delà de la limite. Arrêt, déplacement, autre pad, pause d’arrangement et fin annulent les attaques restantes. Le panneau modifie le pad affiché et se ferme au changement de pad, au repli, à la suppression, Nouveau/Charger/Importer ou Échap.`,
  spanish: `### Propiedades del paso y acordes rasgueados

Clic derecho en una nota melódica o acorde, Mayús+F10 o el botón ⋮ abre Propiedades del paso sobre la cuadrícula. El tiempo sigue disponible en los silencios. Rasgueo ofrece Desactivado, Grave → Agudo y Agudo → Grave. Selecciona un acorde para activar los controles; quitarlo conserva sus valores. Separación es un entero de 0–100% de un paso local, medido desde la primera hasta la última nota. Los milisegundos siguen tempo, compás, subdivisión y velocidad. Al 0% suenan juntas; al 100% la última empieza en el paso siguiente, aunque esté vacío. Desactivado conserva la separación.

Las notas se espacian uniformemente por altura. El tiempo desplaza todo el rasgueo. Cada nota conserva su duración, incluido HOLD, y puede solaparse con pasos posteriores. Una misma altura se vuelve a disparar; si coincide el instante, gana el paso lógico posterior solo para esa altura. A 120 BPM, 4/4, subdivisión 4 y velocidad 1×, tres notas al 40% empiezan a 0, 25 y 50 ms; al 100%, a 0, 62,5 y 125 ms. Los pasos melódicos no tienen controles de repeticiones rápidas.

Las etiquetas de tiempo y porcentaje ↑/↓ reabren el panel. Copias, pasos ocultos, guardados, bundles nativos y exports CSD conservan los valores; Limpiar pasos los restablece. Los cambios de dirección, separación o tiempo se aplican en la siguiente aparición de un rasgueo iniciado; HOLD sigue ajustando los finales. Repetir el mismo pad permite notas tardías más allá del límite. Parada, salto, otro pad, pausa del arreglo y final cancelan ataques pendientes. El panel edita el pad mostrado y se cierra al cambiar de pad, contraer, eliminar, Nuevo/Cargar/Importar o Escape.`
};
