import type { GuiLanguage } from "../types";

export const collapsiblePanelHelp: Record<GuiLanguage, { design: string; runtime: string; perform: string; rack: string }> = {
  "english": {
    "design": "Use Patch controls to collapse metadata and load/save/compile/import/export actions. Instrument tabs, including add and close, stay visible. Controls start expanded; your choice survives view switches until browser reload.",
    "runtime": "Runtime starts collapsed. Open it with Show runtime in the graph header and close it with Hide. Your choice survives view switches until browser reload; compilation and playback continue while it is hidden.",
    "perform": "Click a panel title or focus it and press Enter or Space to collapse or expand its contents. Header actions, status and help remain available. Panels collapse independently, start expanded and remember your choices across view switches until browser reload. Adding a device opens its group. Collapsing preserves edits and does not stop playback. The shared tempo stays outside the sequencer groups. Hidden rack, device, arranger and Mixer contents suspend visual updates and animations, including nested Mixer sections. Expanding restores drafts, selection, clipboard, zoom and scroll with the current playback position. This editor state lasts while Perform is open; New, Load or Import resets it. Collapsing closes temporary menus, cancels drags and releases manually held piano notes; sequenced playback continues.",
    "rack": "When collapsed, the rack keeps Add Instrument and Start/Stop available. A single horizontally scrolling row shows MIDI channel and patch name for every instance, including duplicates; continuous instruments show Continuous instead of a channel. Long names have full-name tooltips. Focus the row and use the arrow keys to scroll. Metadata, file actions and detailed controls return when expanded."
  },
  "german": {
    "design": "Mit Patch-Steuerung werden Metadaten sowie Laden, Speichern, Kompilieren, Import und Export eingeklappt. Instrument-Tabs mit Hinzufügen und Schließen bleiben sichtbar. Die Steuerung startet ausgeklappt; die Auswahl bleibt beim Ansichtswechsel bis zum Neuladen der Browserseite erhalten.",
    "runtime": "Runtime startet eingeklappt. Show runtime in der Graph-Kopfzeile öffnet das Panel, Hide schließt es. Die Auswahl bleibt beim Ansichtswechsel bis zum Neuladen der Browserseite erhalten; Kompilierung und Wiedergabe laufen auch bei verborgenem Panel weiter.",
    "perform": "Zum Ein- oder Ausklappen auf einen Paneltitel klicken oder ihn fokussieren und Enter oder Leertaste drücken. Kopfzeilenaktionen, Status und Hilfe bleiben verfügbar. Panels lassen sich unabhängig einklappen, starten ausgeklappt und behalten die Auswahl beim Ansichtswechsel bis zum Neuladen der Browserseite. Ein neues Gerät öffnet seine Gruppe. Einklappen erhält Änderungen und stoppt die Wiedergabe nicht. Das gemeinsame Tempo bleibt außerhalb der Sequencer-Gruppen. Verborgene Inhalte von Rack, Geräten, Arranger und Mixer setzen Anzeigen und Animationen aus, auch in verschachtelten Mixer-Bereichen. Beim Ausklappen erscheinen Entwürfe, Auswahl, Zwischenablage, Zoom und Scrollposition mit dem aktuellen Wiedergabestand. Dieser Bearbeitungszustand gilt, solange Perform geöffnet ist; Neu, Laden oder Import setzt ihn zurück. Einklappen schließt temporäre Menüs, beendet Ziehgesten und lässt manuell gehaltene Klaviertöne los; die Sequencer spielen weiter.",
    "rack": "Eingeklappt bleiben Instrument hinzufügen und Start/Stopp verfügbar. Eine einzige horizontal scrollbare Zeile zeigt MIDI-Kanal und Patch-Namen jeder Instanz, auch mehrfach geladener Patches; kontinuierliche Instrumente zeigen Dauerhaft statt eines Kanals. Tooltips zeigen lange Namen vollständig. Die Zeile fokussieren und mit den Pfeiltasten scrollen. Metadaten, Dateiaktionen und Detailsteuerungen werden beim Ausklappen wieder sichtbar."
  },
  "french": {
    "design": "Commandes du patch replie les métadonnées et les actions de chargement, enregistrement, compilation, import et export. Les onglets instrument, avec ajout et fermeture, restent visibles. Les commandes sont dépliées au départ ; votre choix est conservé entre les vues jusqu'au rechargement du navigateur.",
    "runtime": "Runtime est replié au départ. Show runtime dans l'en-tête du graphe ouvre le panneau et Hide le ferme. Votre choix est conservé entre les vues jusqu'au rechargement du navigateur ; la compilation et la lecture continuent quand il est masqué.",
    "perform": "Cliquez sur le titre d'un panneau, ou sélectionnez-le au clavier et appuyez sur Entrée ou Espace, pour le replier ou le déplier. Actions, état et aide de l'en-tête restent accessibles. Les panneaux sont indépendants, dépliés au départ et conservent votre choix entre les vues jusqu'au rechargement du navigateur. Ajouter un appareil ouvre son groupe. Replier conserve les modifications et ne stoppe pas la lecture. Le tempo commun reste hors des groupes de séquenceurs. Les contenus masqués du rack, des appareils, de l’arrangeur et du Mixer suspendent leurs affichages et animations, y compris les sections imbriquées du Mixer. Déplier restaure brouillons, sélection, presse-papiers, zoom et défilement à la position de lecture actuelle. Cet état dure tant que Perform est ouvert ; Nouveau, Charger ou Importer le réinitialise. Replier ferme les menus temporaires, annule les glissements et relâche les notes de piano tenues manuellement ; les séquenceurs continuent.",
    "rack": "Le rack replié conserve Ajouter instrument et Démarrer/Arrêter. Une seule ligne à défilement horizontal affiche canal MIDI et nom du patch pour chaque instance, y compris les doublons ; les instruments continus affichent Continue à la place du canal. Les infobulles montrent les noms longs en entier. Sélectionnez la ligne au clavier puis utilisez les flèches pour défiler. Dépliez pour retrouver métadonnées, actions de fichier et commandes détaillées."
  },
  "spanish": {
    "design": "Controles del patch contrae los metadatos y las acciones de cargar, guardar, compilar, importar y exportar. Las pestañas de instrumentos, con agregar y cerrar, siguen visibles. Los controles empiezan expandidos; tu elección se conserva al cambiar de vista hasta recargar el navegador.",
    "runtime": "Runtime empieza contraído. Show runtime en la cabecera del grafo abre el panel y Hide lo cierra. Tu elección se conserva al cambiar de vista hasta recargar el navegador; la compilación y la reproducción continúan mientras está oculto.",
    "perform": "Haz clic en el título de un panel, o enfócalo con el teclado y pulsa Intro o Espacio, para contraerlo o expandirlo. Las acciones, el estado y la ayuda de la cabecera siguen disponibles. Los paneles son independientes, empiezan expandidos y conservan tu elección entre vistas hasta recargar el navegador. Agregar un dispositivo abre su grupo. Contraer conserva las ediciones y no detiene la reproducción. El tempo compartido queda fuera de los grupos de secuenciadores. Los contenidos ocultos del rack, los dispositivos, el arreglador y Mixer suspenden sus vistas y animaciones, incluidas las secciones anidadas de Mixer. Expandir restaura borradores, selección, portapapeles, zoom y desplazamiento con la posición de reproducción actual. Este estado dura mientras Perform esté abierto; Nuevo, Cargar o Importar lo reinicia. Contraer cierra menús temporales, cancela arrastres y libera las notas de piano mantenidas manualmente; los secuenciadores continúan.",
    "rack": "El rack contraído conserva Agregar instrumento e Iniciar/Detener. Una sola fila con desplazamiento horizontal muestra canal MIDI y nombre del patch por instancia, incluidos duplicados; los instrumentos continuos muestran Continua en lugar del canal. Las descripciones emergentes muestran los nombres largos completos. Enfoca la fila y usa las flechas para desplazarte. Al expandir vuelven los metadatos, las acciones de archivo y los controles detallados."
  }
};
