import type { GuiLanguage } from "../types";

export const patternWorkspaceHelp: Record<GuiLanguage, string> = {
  english: `## Pattern workspace for all sequencers

The always-visible workspace sits at the upper right, or below musical controls on narrow screens. Pads turn green only for playable notes or active hits with velocity above zero. Empty, hold-only and zero-velocity pads stay dark; selection and queued outlines remain independent.

Drag pads or saved phrases into Free workspace, then drag to reorder. Cmd/Ctrl-click toggles selection; Shift-click selects a range. Group gathers at least two selected pads/rests in their displayed order, even when separated, and replaces them at the first selected position. Supergroup also accepts groups. These actions save reusable definitions immediately. Right-click or Shift+F10 opens Edit, Group, Supergroup, Ungroup and Remove. Ungroup expands one level while retaining the definition. Delete/Backspace removes selected occurrences and closes the gap. Add rest offers 1, 2, 4, 8 or 16 local beats. Pad-to-pad dragging still copies the pad.

Choose a saved phrase or double-click a group to edit its draft. Apply changes every use; duration changes shift following arrangement material. Save as new makes an independent copy; Discard changes restores the saved contents. Each phrase and the free workspace retain separate drafts across collapse and view switches. New/Load/Import/reload clears drafts. Loose items and unapplied edits are never saved or exported. Only saved arrangement or phrase references block Delete definition. Temporary workspace references expand into the saved contents, preserving the assembly; the deleted definition’s own draft is removed. Empty referenced definitions and edits exceeding 256 expanded tokens are rejected. Song order is edited only in the arranger.

Play loops the whole displayed workspace; an amber outline follows its currently playing pad, group, supergroup or rest, independently of selection. The outline pauses during speaker previews and resumes on release. Stop restores prior playback. Edits update a playing workspace after 80 ms at the next cycle boundary. A speaker held for 250 ms temporarily previews its item, repeating until release. Short clicks do nothing. With the arranger running, previews start at the next lane cycle boundary; while stopped, at an audio block without moving the song cursor. Space/Enter supports hold/release. Speaker release restores workspace playback, if active, at its current position; workspace Stop then restores the original lane state. Collapse/navigation cancels both; transport Play/Stop clears restoration so late replies cannot restart playback. Preparation failures retain the previous sound and edited draft. Controller and arpeggiator editors use this same workspace. A controller pad with just two zero-valued endpoints stays dark; extra points or nonzero values mark content. Zero remains a valid CC value. Arpeggiator pads need a note-producing step with positive velocity and probability; rests and ties alone stay dark. In Live mode, workspace Play and speakers follow the configured next rhythm cycle or master bar when a clock is established, otherwise an audio block. Phrase lengths use pad duration. Incoming or held notes are required; no test chord is supplied. Hold, Active/Bypass/Mute and current chord changes remain effective. Release restores the underlying Live pulse. Live mode hides arrangement-only controls; Launch pad remains separate from temporary previews.`,
  german: `## Pattern-Arbeitsfläche für alle Sequencer

Die stets sichtbare Arbeitsfläche liegt oben rechts, auf schmalen Bildschirmen unter den musikalischen Einstellungen. Pads sind nur grün, wenn abspielbare Noten oder aktive Schläge mit Velocity über null enthalten sind. Leere Pads, reine Holds und Velocity null bleiben dunkel; Auswahl und Vormerkung haben eigene Umrandungen.

Pads oder gespeicherte Phrasen in die freie Arbeitsfläche ziehen und dort umordnen. Cmd/Strg-Klick schaltet die Auswahl um; Umschalt-Klick wählt einen Bereich. Gruppieren fasst mindestens zwei gewählte Pads/Pausen in sichtbarer Reihenfolge am ersten gewählten Platz zusammen, auch bei getrennter Auswahl. Supergruppen erlauben zusätzlich Gruppen. Diese Aktionen speichern wiederverwendbare Definitionen sofort. Rechtsklick oder Umschalt+F10 bietet Bearbeiten, Gruppieren, Supergruppe, Gruppe auflösen und Entfernen. Auflösen erweitert eine Ebene und behält die Definition. Entf/Rücktaste entfernt gewählte Vorkommen und schließt die Lücke. Pausen gibt es für 1, 2, 4, 8 oder 16 lokale Beats. Ziehen zwischen den acht Pads kopiert weiterhin das Pad.

Eine gespeicherte Phrase wählen oder eine Gruppe doppelklicken, um ihren Entwurf zu bearbeiten. Übernehmen ändert alle Verwendungen; Längenänderungen verschieben nachfolgendes Arrangement-Material. Als neu speichern erstellt eine unabhängige Kopie; Änderungen verwerfen stellt die gespeicherten Inhalte wieder her. Entwürfe bleiben getrennt je Phrase und freier Arbeitsfläche beim Einklappen und Ansichtswechsel erhalten. Neu/Laden/Import/Neuladen setzt sie zurück. Lose Elemente und nicht übernommene Änderungen werden nie gespeichert oder exportiert. Nur gespeicherte Arrangement- oder Phrasenverweise sperren Definition löschen. Temporäre Arbeitsflächenverweise werden in die gespeicherten Inhalte aufgelöst; die Zusammenstellung bleibt erhalten. Der eigene Entwurf der gelöschten Definition wird entfernt. Referenzierte Definitionen dürfen nicht leer übernommen werden; maximal 256 expandierte Tokens. Nur der Arranger bearbeitet die Songfolge.

Play wiederholt die gesamte angezeigte Arbeitsfläche. Eine gelbe Umrandung folgt dem aktuell spielenden Pad, der Gruppe, Supergruppe oder Pause, unabhängig von der Auswahl. Während einer Lautsprechervorschau verschwindet sie und kehrt beim Loslassen zurück. Stopp stellt die vorherige Wiedergabe wieder her. Änderungen werden nach 80 ms an der nächsten Zyklusgrenze übernommen. Ein Lautsprecher startet nach 250 ms Halten eine Vorschau bis zum Loslassen. Kurze Klicks bewirken nichts. Bei laufendem Arranger startet sie an der nächsten Spur-Zyklusgrenze, im Stopp am Audioblock ohne Bewegung des Song-Cursors. Leertaste/Enter unterstützt Halten/Loslassen. Loslassen stellt die aktive Arbeitsfläche an der aktuellen Position wieder her; deren Stopp stellt den ursprünglichen Spurzustand wieder her. Einklappen/Navigation beendet beide Ebenen; Transport-Play/Stopp löscht die Wiederherstellung. Vorbereitungsfehler behalten den bisherigen Klang und Entwurf. Controller und Arpeggiatoren verwenden dieselbe Arbeitsfläche. Controller-Pads mit nur zwei Endpunkten bei null bleiben dunkel; zusätzliche Punkte oder Werte ungleich null markieren Inhalt. Null bleibt ein gültiger CC-Wert. Arpeggiator-Pads benötigen einen notenerzeugenden Schritt mit positiver Velocity und Wahrscheinlichkeit; reine Pausen und Bindungen bleiben dunkel. Im Live-Modus starten Arbeitsfläche und Lautsprecher je nach Einstellung am nächsten Rhythmuszyklus oder Master-Takt, ohne etablierten Takt am Audioblock. Die Pad-Dauer bestimmt die Phrasenlänge. Eingehende oder gehaltene Noten sind erforderlich; es gibt keinen Testakkord. Hold, Aktiv/Bypass/Stumm und aktuelle Akkordwechsel bleiben wirksam. Loslassen stellt den zugrunde liegenden Live-Puls wieder her. Arrangement-Bedienelemente sind in Live ausgeblendet; Pad starten bleibt von Vorschauen getrennt.`,
  french: `## Atelier de motifs pour tous les séquenceurs

L’atelier reste visible en haut à droite, ou sous les réglages musicaux sur un écran étroit. Un pad devient vert seulement avec une note jouable ou un coup actif de vélocité supérieure à zéro. Les pads vides, les tenues seules et la vélocité nulle restent sombres ; sélection et attente gardent leurs contours distincts.

Glissez des pads ou phrases enregistrées dans Assemblage libre, puis déplacez-les pour les réordonner. Cmd/Ctrl-clic bascule la sélection ; Maj-clic sélectionne une plage. Grouper rassemble au moins deux pads/silences sélectionnés dans l’ordre affiché, même séparés, à la première position sélectionnée. Supergroupe accepte aussi des groupes. Ces actions enregistrent immédiatement les définitions. Clic droit ou Maj+F10 propose Modifier, Grouper, Supergroupe, Dissocier et Retirer. Dissocier développe un niveau et conserve la définition. Suppr/Retour arrière retire la sélection et ferme l’espace. Ajouter un silence propose 1, 2, 4, 8 ou 16 temps locaux. Glisser un des huit pads sur un autre copie toujours le pad.

Choisissez une phrase enregistrée ou double-cliquez un groupe pour modifier son brouillon. Appliquer modifie toutes ses utilisations ; la durée décale la suite de l’arrangement. Enregistrer une copie crée une définition indépendante ; Annuler les modifications restaure le contenu enregistré. Chaque phrase et l’assemblage libre gardent leurs brouillons séparés après fermeture du panneau ou changement de vue. Nouveau/Charger/Importer/rechargement les efface. Les éléments libres et changements non appliqués sont exclus de la sauvegarde et des exports. Seules les références enregistrées dans un arrangement ou une phrase bloquent Supprimer la définition. Les références temporaires sont développées en leur contenu enregistré, préservant l’assemblage ; le brouillon propre à la définition supprimée est retiré. Une définition utilisée ne peut pas devenir vide ; limite de 256 éléments développés. Seul l’arrangeur modifie l’ordre du morceau.

Lecture répète tout l’assemblage affiché. Un contour ambre suit le pad, groupe, supergroupe ou silence en cours, indépendamment de la sélection. Il disparaît pendant l’aperçu au haut-parleur et revient au relâchement. Arrêt restaure la lecture précédente. Les modifications suivent 80 ms puis la prochaine limite de cycle. Maintenir un haut-parleur 250 ms lance un aperçu jusqu’au relâchement. Les clics brefs ne font rien. Pendant l’arrangement, il démarre à la prochaine limite de cycle ; à l’arrêt, au bloc audio sans déplacer le curseur du morceau. Espace/Entrée permet le même geste. Relâcher restaure l’assemblage actif à sa position actuelle ; arrêter cet assemblage restaure l’état initial de la piste. Fermer/naviguer annule les deux niveaux ; Play/Stop du transport efface leur restauration. Un échec conserve le son précédent et le brouillon. Les contrôleurs et arpégiateurs utilisent le même atelier. Un pad contrôleur avec seulement deux extrémités à zéro reste sombre ; des points supplémentaires ou valeurs non nulles indiquent du contenu. Zéro reste une valeur CC valide. Un pad arpégiateur doit contenir un pas produisant des notes avec vélocité et probabilité positives ; silences et liaisons seuls restent sombres. En Live, la lecture et les haut-parleurs suivent le prochain cycle rythmique ou la prochaine mesure maître selon le réglage, ou un bloc audio sans horloge établie. La durée du pad définit les phrases. Des notes entrantes ou maintenues sont nécessaires ; aucun accord de test n’est fourni. Hold, Actif/Bypass/Muet et les changements d’accord restent effectifs. Relâcher restaure la pulsation Live précédente. Les commandes propres à l’arrangement sont masquées en Live ; Lancer le pad reste distinct des aperçus.`,
  spanish: `## Taller de patrones para todos los secuenciadores

El taller permanece visible arriba a la derecha, o debajo de los ajustes musicales en pantallas estrechas. Un pad es verde solo cuando contiene una nota reproducible o un golpe activo con velocidad mayor que cero. Los pads vacíos, con solo sostenidos o velocidad cero quedan oscuros; selección y espera conservan contornos propios.

Arrastra pads o frases guardadas al Montaje libre y reordénalos arrastrando. Cmd/Ctrl-clic alterna la selección; Mayús-clic selecciona un intervalo. Agrupar reúne al menos dos pads/silencios seleccionados en su orden visible, aunque estén separados, en la primera posición seleccionada. Supergrupo también admite grupos. Estas acciones guardan inmediatamente definiciones reutilizables. Clic derecho o Mayús+F10 ofrece Editar, Agrupar, Supergrupo, Desagrupar y Quitar. Desagrupar expande un nivel y conserva la definición. Supr/Retroceso quita la selección y cierra el hueco. Añadir silencio ofrece 1, 2, 4, 8 o 16 pulsos locales. Arrastrar uno de los ocho pads sobre otro sigue copiándolo.

Elige una frase guardada o haz doble clic en un grupo para editar su borrador. Aplicar modifica todos sus usos; la duración desplaza el material posterior del arreglo. Guardar como nuevo crea una copia independiente; Descartar cambios restaura el contenido guardado. Cada frase y el montaje libre mantienen borradores separados al contraer o cambiar de vista. Nuevo/Cargar/Importar/recargar los borra. Los elementos sueltos y cambios sin aplicar no se guardan ni exportan. Solo las referencias guardadas en un arreglo o frase bloquean Eliminar definición. Las referencias temporales se expanden en su contenido guardado y conservan el montaje; se elimina el borrador propio de la definición. Una definición utilizada no puede aplicarse vacía; límite de 256 elementos expandidos. Solo el arreglador edita el orden del tema.

Reproducir repite todo el montaje mostrado. Un contorno ámbar sigue el pad, grupo, supergrupo o silencio que está sonando, independientemente de la selección. Desaparece durante la escucha con el altavoz y vuelve al soltarlo. Detener restaura la reproducción anterior. Los cambios se aplican tras 80 ms en el siguiente límite de ciclo. Mantener un altavoz 250 ms inicia una escucha hasta soltarlo. Los clics breves no hacen nada. Durante el arreglo empieza en el siguiente límite de ciclo; detenido, en un bloque de audio sin mover el cursor. Espacio/Intro permite el mismo gesto. Soltar restaura el montaje activo en su posición actual; detenerlo restaura el estado original de la pista. Contraer/navegar cancela ambos niveles; Play/Stop del transporte borra la restauración. Un fallo conserva el sonido anterior y el borrador. Los controladores y arpegiadores usan el mismo taller. Un pad controlador con solo dos extremos en cero queda oscuro; puntos adicionales o valores distintos de cero indican contenido. Cero sigue siendo un valor CC válido. Un pad arpegiador necesita un paso que produzca notas con velocidad y probabilidad positivas; solo silencios o ligaduras quedan oscuros. En Live, la reproducción y los altavoces esperan al próximo ciclo rítmico o compás maestro configurado, o a un bloque de audio sin reloj establecido. La duración del pad define las frases. Se requieren notas entrantes o retenidas; no se genera un acorde de prueba. Hold, Activo/Bypass/Silencio y los cambios de acorde siguen vigentes. Soltar restaura el pulso Live anterior. Live oculta los controles exclusivos del arreglo; Lanzar pad sigue separado de las escuchas temporales.`
};
