import type { GuiLanguage } from "../types";

const rows = {
  left: ["Left", "Links", "Gauche", "Izquierda"],
  right: ["Right", "Rechts", "Droite", "Derecha"],
  apply: ["Apply", "Anwenden", "Appliquer", "Aplicar"],
  cancel: ["Cancel", "Abbrechen", "Annuler", "Cancelar"],
  preview: ["Review stereo changes", "Stereo-Änderungen prüfen", "Vérifier les modifications stéréo", "Revisar cambios estéreo"],
  groupExisting: ["Group existing channels", "Vorhandene Kanäle gruppieren", "Grouper les canaux existants", "Agrupar canales existentes"],
  convert: ["Convert Direct Audio Output", "Direkten Audioausgang konvertieren", "Convertir la sortie audio directe", "Convertir salida de audio directa"],
  repair: ["Repair", "Reparieren", "Réparer", "Reparar"],
  createMissing: ["Create missing channels", "Fehlende Kanäle erstellen", "Créer les canaux manquants", "Crear canales ausentes"],
  removeMapping: ["Remove mapping", "Zuordnung entfernen", "Supprimer la correspondance", "Eliminar asignación"],
  choose: ["Choose a node", "Knoten wählen", "Choisir un nœud", "Elegir un nodo"],
  formula: ["Remove input formula", "Eingabeformel entfernen", "Supprimer la formule d’entrée", "Eliminar fórmula de entrada"],
  invalidNames: ["Choose two distinct, nonempty channel names that are not already in use. Reserved direct-output names cannot be renamed.", "Zwei verschiedene, nicht leere und unbenutzte Kanalnamen wählen. Reservierte direkte Ausgangsnamen können nicht umbenannt werden.", "Choisissez deux noms de canaux distincts, non vides et disponibles. Les noms réservés des sorties directes ne peuvent pas être renommés.", "Elija dos nombres de canal distintos, no vacíos y disponibles. Los nombres reservados de salida directa no se pueden renombrar."],
  missingMembers: ["This mapping has missing channels. Repair it or remove the mapping.", "Dieser Zuordnung fehlen Kanäle. Reparieren oder die Zuordnung entfernen.", "Des canaux manquent dans cette correspondance. Réparez-la ou supprimez-la.", "Faltan canales en esta asignación. Repárela o elimínela."],
  ambiguousMembers: ["Multiple nodes use the same channel name. Give them unique names before grouping.", "Mehrere Knoten verwenden denselben Kanalnamen. Vor dem Gruppieren eindeutige Namen vergeben.", "Plusieurs nœuds utilisent le même nom de canal. Donnez-leur des noms uniques avant de les grouper.", "Varios nodos usan el mismo nombre de canal. Asígneles nombres únicos antes de agruparlos."],
  overlappingMembers: ["These channels belong to another mapping. Remove that mapping before regrouping.", "Diese Kanäle gehören zu einer anderen Zuordnung. Diese vor dem Umgruppieren entfernen.", "Ces canaux appartiennent à une autre correspondance. Supprimez-la avant de les regrouper.", "Estos canales pertenecen a otra asignación. Elimínela antes de reagruparlos."],
  dynamicMembers: ["A channel name is unresolved or driven by an expression. Use a literal name before grouping.", "Ein Kanalname ist unaufgelöst oder wird durch einen Ausdruck gesteuert. Vor dem Gruppieren einen festen Namen verwenden.", "Un nom de canal est indéterminé ou défini par une expression. Utilisez un nom littéral avant de grouper.", "Un nombre de canal no está resuelto o depende de una expresión. Use un nombre literal antes de agrupar."],
  routes: ["Affected routes in the current performance", "Betroffene Verbindungen in der aktuellen Performance", "Routes concernées dans la performance actuelle", "Rutas afectadas en la interpretación actual"],
  routeNotice: ["External ports change. Repair affected routes in the mixer after saving. Other saved performances are not updated.", "Externe Ports ändern sich. Betroffene Verbindungen nach dem Speichern im Mixer reparieren. Andere gespeicherte Performances werden nicht aktualisiert.", "Les ports externes changent. Réparez les routes concernées dans le mixeur après enregistrement. Les autres performances enregistrées ne sont pas mises à jour.", "Los puertos externos cambian. Repare las rutas afectadas en el mezclador después de guardar. Las demás interpretaciones guardadas no se actualizan."],
  noRoutes: ["None", "Keine", "Aucune", "Ninguna"],
  inputHelp: ["Creates a stereo mapping and two named inleta channels. Its Left and Right audio outputs receive signals routed from other instruments in the performance. It does not capture the hardware audio input. Expand the block to inspect its ordinary opcodes.", "Erstellt eine Stereo-Zuordnung und zwei benannte inleta-Kanäle. Die Audioausgänge Links und Rechts empfangen Signale anderer Instrumente der Performance. Dies ist kein Hardware-Audioeingang. Den Block ausklappen, um die normalen Opcodes zu sehen.", "Crée une correspondance stéréo et deux canaux inleta nommés. Ses sorties audio Gauche et Droite reçoivent les signaux d’autres instruments de la performance. Il ne capture pas l’entrée audio matérielle. Dépliez le bloc pour voir ses opcodes ordinaires.", "Crea una asignación estéreo y dos canales inleta con nombre. Sus salidas de audio Izquierda y Derecha reciben señales de otros instrumentos de la interpretación. No captura la entrada de audio del dispositivo. Expanda el bloque para ver sus opcodes ordinarios."],
  outputHelp: ["Creates a stereo mapping and two named outleta channels. Connect signals to Left and Right, then route these ports in the performance mixer. Direct Audio Output (outs) sends to the audio output instead. Deleting this block or its mapping removes both channels and their connections; deleting one expanded channel ungroups the survivor.", "Erstellt eine Stereo-Zuordnung und zwei benannte outleta-Kanäle. Signale mit Links und Rechts verbinden und diese Ports im Performance-Mixer routen. Direct Audio Output (outs) sendet zum Audioausgang. Das Löschen des Blocks oder seiner Zuordnung entfernt beide Kanäle samt Verbindungen; beim Löschen eines ausgeklappten Kanals bleibt der andere ungruppiert erhalten.", "Crée une correspondance stéréo et deux canaux outleta nommés. Connectez les signaux à Gauche et Droite, puis routez ces ports dans le mixeur. Direct Audio Output (outs) envoie vers la sortie audio. Supprimer ce bloc ou sa correspondance supprime les deux canaux et leurs connexions ; supprimer un canal déplié dégroupe le canal restant.", "Crea una asignación estéreo y dos canales outleta con nombre. Conecte señales a Izquierda y Derecha y dirija estos puertos en el mezclador. Direct Audio Output (outs) envía a la salida de audio. Eliminar este bloque o su asignación elimina ambos canales y conexiones; eliminar un canal expandido desagrupa el restante."],
} as const;
export function stereoCopy(language: GuiLanguage) {
  const index = { english: 0, german: 1, french: 2, spanish: 3 }[language];
  return (key: keyof typeof rows): string => rows[key][index];
}
